#!/bin/bash
cp -p /home/boazn/public/02ws.com/public/images/webCamera.jpg /home/boazn/public/02ws.com/public/images/alldaypics/webcam`date +%y%m%d%H%M`.jpg
cp -p /home/boazn/public/02ws.com/public/images/webCameraB.jpg /home/boazn/public/02ws.com/public/images/alldaypics/webcamB`date +%y%m%d%H%M`.jpg