#!/bin/bash
# wget -d -O /home/boazn/public/02ws.com/public/images/radar/imsradar`date +%y%m%d%H%M`.jpg 'http://www.ims.gov.il/Ims/Pages/RadarImage.aspx?Row=9&TotalImages=10&LangID=1&Location=' 
curl --connect-timeout 120 --retry 2 -m 120 -o  /home/boazn/public/02ws.com/public/images/radar/imsradar`date +%y%m%d%H%M`.jpg 'http://www.ims.gov.il/Ims/Pages/RadarImage.aspx?Row=9&TotalImages=10&LangID=1&Location=' 
