' VBS Script Generated by CuteFTP (TM) macro recorder.
' Generated at: 21/12/2013 01:51:03.

' Create TEConnection object
Set MySite = CreateObject("CuteFTPPro.TEConnection")

' Initialize remote server host name, protocol, port, etc.
MySite.Host = "176.58.97.97"
MySite.Protocol = "SFTP"
MySite.Port = 22
MySite.Retries = 30
MySite.Delay = 30
MySite.MaxConnections = 4
MySite.TransferType = "AUTO"
MySite.DataChannel = "DEFAULT"
MySite.AutoRename = "OFF"
' WARNING!!! SENSITIVE DATA: user name and password.
MySite.Login = "root"
MySite.Password = "bn19za72"
MySite.SocksInfo = ""
MySite.ProxyInfo = ""
' Connect to remote server
MySite.Connect
MySite.Upload "D:\web\site\weather\Station\fulldata.xml", "/home/boazn/public/02ws.com/public/tempfulldata.xml"
MySite.RemoteRemove "/home/boazn/public/02ws.com/public/fulldata.xml"
MySite.RemoteRename "/home/boazn/public/02ws.com/public/tempfulldata.xml", "/home/boazn/public/02ws.com/public/fulldata.xml"
MySite.Disconnect
