<?php
if (!defined('INTERVAL'))
    define("INTERVAL",10);
$CURRENT_SIG_WEATHER = array("Now" , "מה עכשיו", "Сейчас","");
$WEATHER_NEARBY = array("Weather nearby", "מה קורה באזור?", "Погода поблизости","");
$STATIONS_NEARBY = array("More stations in Jerusalem", "עוד תחנות בי-ם", "Ещё установки в Иерусалиме","");
$HOME_PAGE = array("To the home page" , "לעמוד הראשי", "Перейти на главную страницу","");
$MOBILE_FRIENDLY = array("Mobile friendly" , "מותאם לנייד", "Мобильная версия","");
$WHATS_NEW = array("What's new" , "מה חדש", "Что нового","");
$CHOOSE = array("Choose month or year", "בחר חודש או שנה", "Выберите месяц или год","");
$GUESTBOOK = array("GuestBook" , "ספר אורחים", "Гостевая книга","");
$MODELS = array("Models" , "מודלים", "Модули","");
$CONTACT_INFO = array("About" , "אודות", "О программе","");
$LOCATION = array("Location" , "מיקום", "Географическое расположение","");
$CONTACT_ME = array("Contact", "צרו קשר", "Обратная связь","");
$START = array("Start", "התחל", "Старт","");
$LINKS = array("Links", "קישורים", "Ссылки","");
$AD_LINK = array("Ad link to message body", "הוספת קישור לגוף ההודעה", "Добавить ссылку в сообщение","");
$ITALIC = array("Italic selected text in message body", "הדגשה של טקסט מסומן בגוף ההודעה", "Выделение выбранного текста в сообщении","");
$LINK = array("the link", "הקישור", "Ссылка","");
$DICTIONARY = array("Dictionary", "מונחון", "Глоссарий","");
$LINK_TITLE = array("link title", "כותרת לקישור", "Заглавие ссылки","");
$GET_UPDATES = array("Get alarms by Email", "קבלו התראות באימייל", "Получать оповещения по Электронной Почте","");
$PERSONAL_COLD_METER = array("Pesonal Cold Meter", "מדד קור מותאם אישית", "Личная шкала холода","");
$PERSONAL_COLD_METER_ALERT = array("You can use personal cold meter by selecting it in your account", "מדד קור מותאם אישית לפי ההצבעות שלכם אפשרי תחת פרופיל החשבון שלכם.", "Через личный кабинет можно включить настройку личной шкалы холода","");
$UPDATES_INTERVAL = array("Updates every ".INTERVAL." min", " מתעדכן כל ".INTERVAL." דקות", "Обновлять каждые ".INTERVAL." минут(ы)","");
$BANNER_FLASH_VIEW = array("Online mode", "מצב אונליין", "Онлайн-режим","");
$CELL_VIEW = array("Page for cell phone", "דף לפלאפון", "Страница для телефона","");
$IPHONE = array("Smartphone", "סמארטפון", "Смартфон","");
$WAP_VIEW = array("WAP page", "WAP", "Страница WAP","");
$TEMP = array("temperature" , "טמפרטורה", "температура","");
$HUMIDITY = array("humidity" , "לחות", "влажность","");
$RAIN = array("rain" , "גשם", "дождь","");
$RAIN_RATE = array("Rain rate" , "עוצמת גשם", "Характер дождя","");
$PRECIPITATION = array("precipitation", "משקעים", "осадки","");
$BAR = array("Pressure" , "לחץ-אוויר", "Атмосферное давление","");
$WIND = array("wind" , "רוח", "ветер","");
$VISIBILITY = array("Visibility", "ראות", "видимость","");
$SUNSHINEHOURS = array("sunshine hours" , "שעות שמש", "световой день ","");
$LOW_RAD = array("Turn on the boiler", "כדאי להדליק את הבוילר", "Сегодня будет мало солнца, стоит подумать о бойлере","");
$RADIATION = array("radiation" , "קרינה", "излучение ","");
$SOLAR_ENERGY = array("solar energy" , "אנרגיה סולרית", "солнечная энергия ","");
$UV = array("UV" , "UV", "УФ","");
$UV_DOSE = array("UV Dose" , "UV מנות", "Доза УФ","");
$HIGH_UV = array("High and dangerous UV", "קרינה מסוכנת", "Опасный уровень УФ","");
$ET = array("Evapotranspiration", "אידוי", "Количество испарения","");
$HIGH_ET = array("Irrigation needed", "הצמחים צמאים", "Стоит подумать о поливе	","");
$KNOTS = array("knots", "קשר", "узлов","");
$KMH = array("km/h", "קמש", "км/ч","");
$BAR_UNIT = array("mb", "מ''ב", "мб ","");
$RAIN_UNIT = array("mm", "מ''מ", "мм","");
$WIND_UNIT = array("km/h", "קמש", "км/час","");
$RAINRATE_UNIT = array("mm/hr", "מ''מ\שעה", "мм/час","");
$SNOW_UNIT = array("cm", "ס''מ", "см","");
$KM = array("km", "קמ", "км","");
$MINTS = array("min", "דק'", "мин","");
$HOUR = array("hour", "שעה", "час","");
$HOURS = array("hrs", "ש'", "часов ","");
$A_BIT = array("a bit", "קצת", "немного","");
$CLOSE_TO = array("close to", "קרוב ל-", "около","");
$SNOW_JER = array("Snow in Jerusalem", "שלג בירושלים", "Снег в Иерусалиме","");
$SNOW_PICTURES = array("Snow pictures from that day", "תמונות שלג מהאירוע", "Фотографии снега этого дня ","");
$SEND_PICTURES = array("Send picture", "שליחת תמונה", "Послать фотографию","");
$SONGS = array("Weather Songs", "שירי מזג-אוויר", "Песни О Погоде ","");
$MYTHS = array("Myths", "מיתוסים", "Мифы","");
$LIGHTS = array("Lightning maps", "מפות ברקים", "Карты молний","");
$ARCHIVE = array("Archive", "ארכיון", "Архив","");
$FORECASTER_JOB = array("Forecast job", "יום בחיי חזאי", "Работа прогнозиста","");
$WIND_CHILL = array("wind Chill", "אפקט קרור הרוח", "ветер холодит","");
$IT_FEELS = array("feels like", "מרגיש כמו", "ощущается как","");
$IN_THE_SUN = array("sun", "בשמש", "на солнце","");
$THW = array("feeled temperature", "טמפרטורה מוחשית", "ощущаемая температура","");
$SUMMARY = array("Summary", "סיכום", "Резюме","");
$ELEVATION = array("Height", "גובה", "высота","");
$METERS = array("m", "מ'", "от","");
$CHANGE_STYLE = array("Change style", "שנה עיצוב", "Изменить интерфейс","");
$GOING_DOWN = array("going down", "במגמת ירידה", "понижение","");
$GOING_UP = array("going up", "במגמת עליה", "подъём","");
$MORE_INFO = array("more", "עוד", "еще","");
$WHAT_ELSE = array("What's now?", "מה עוד קורה עכשיו", "Что твориться сейчас","");
$WHAT_MORE = array("Alerts & more", "התראות ועוד", "Оповещения и дополнительные функции","");
$CURRENT_ENERGY = array("and what with the energy?", "נו, ומה עם האנרגיה?", "а что там с энергией?","");
$STORM_POWER = array("Storm Power", "מדדי חוזק המערכת", "Грозовой индикатор","");
$RAIN_RADAR = array("Radar", "מכ''ם גשם", "Радар дождя	","");
$LAST_UPDATE = array("updated at", "עדכון אחרון: ", "Последние обновление","");
$DETAILED_TABLE = array("Last day intervaled data", "יום-יומיים אחרונים בטבלה", "Последние день-два в таблице","");
$DETAILED_TABLE08 = array("Last week intervaled data", "שבוע אחרון בטבלה", "Последняя неделя в таблице","");
$WIND_DISTRIBUTION = array("Hours of wind distribution", "התפלגות הרוח על פני שעות אחרונות", "Почасовое распределение ветра","");
$CLIMATE = array("Climate", "אקלים", "Климат","");
$CLIMATE_TITLE = array("The unique climate of Jerusalem", "האקלים הייחודי של ירושלים", "Уникальный климат Иерусалима","");
$LOADING = array("loading", "טוען", "загрузка","");
$SHARE = array("Share", "שיתוף", "Поделиться","");
$FAQ = array("FAQ", "שאלות ותשובות", "ЧАВО","");
$TIPS = array("TIPS", "טיפים", "Советы","");
$TIP = array("Tip", "טיפ", "Совет","");
$CLOTH = array("Cloth", "לבוש", "ткань","");
$PIC_OF_THE_DAY = array("Pic of the day", "תמונת היום", "Фото дня","");
$USERS_PICS = array("Users Pics", "תמונות הגולשים", "Фотографии пользователей","");
$COMMENTS = array("Comments", "הערות", "Комментарии","");
$CREATE_NEW_MSG = array("New message", "הודעה חדשה", "Новое сообщение","");
$LOGIN = array("Sign in", "התחברות", "Вход","");
$LOGIN_GREETING = array("Nice to see you again", "שמחים לראות אתכם שוב", "Вход","");
$SIGN_OUT = array("Sign out", "התנתקות", "Выход","");
$REGISTER = array("Sign up", "הרשמה", "Регистрация","");
$NEW_TO_02WS = array("New to 02ws?", "חדש לכם?", "Новое в 02WS?","");
$FORGOT_PASS = array("Reset password", "שכחתי סיסמה", "Забыли пароль","");
$FORGOT_PASS_REQ = array("Send me password reset to this email", "שלחו לי איפוס ססמה לאימייל הזה", "Забыли пароль","");
$EMAIL = array("Email", "האימייל שלך", "Электронная Почта","");
$PASSWORD = array("Password", "סיסמה", "Пароль","");
$USER_ICON = array("Icon", "אייקון", "Иконка","");
$REMEMBER_ME = array("Remember me", "זכור אותי", "Запомнить меня","");
$NEW_PASSWORD = array("New password", "סיסמא חדשה", "Новый Пароль","");
$PASSWORD_VERIFICATION = array("Password verification", "אימות סיסמה", "Подтверждение пароля","");
$USER_ID = array("User ID", "שם משתמש", "Имя пользователя","");
$DISPLAY_NAME = array("Display name", "שם לתצוגה", "Отображаемое имя","");
$NICE_NAME = array("Nice name", "שם רשמי", "Полное имя","");
$UPDATE_PROFILE = array("Update profile",  "עדכון חשבון", "Изменить настройки учётной записи","");
$REGISTER_SUGGEST = array("If you register (1-2 min issue) you can get your own cold meter suggetions and can view your votes.",  ".אם תרשמו (עניין של דקה-שתיים) תוכלו לקבל גם מדד קור מותאם להצבעתכם האישית ותוכלו גם לצפות בכל ההצבעות ", "Изменить настройки учётной записи","");
$ANONYMOUS_COLDMETER = array("want to stay anonymous", "לא רוצה להישאל שוב", "","");
$MY_VOTES = array("My Votes",  "ההצבעות שלי", "Мои Голосования","");
$IS_TAKEN = array("is taken", "תפוס", "занят","");
$USER_LOCKED = array("User is locked", "חשבון חסום", "Пользователь заблокирован","");
$DONE = array("Done", "בוצע", "Готово","");
$EMPTY = array("empty", "ריק", "пусто","");
$IM = array("I am", "אני", "Я","");
$REGISTRATION_TO_02WS = array("Registration to 02WS", "הרשמה לאתר ירושמיים", "Регистрация на сайте 02WS","");
//////////////////////////////////////////////////////////////////
$FORECAST_TITLE = array("Forecast", "תחזית", "Прогноз","");
$FORECAST_4D = array("Daily", "יומי", "Следующие дни","");
$FORECAST_ABROD = array("World Forecast", "תחזית לחו''ל  - ארה''ב, אירופה, אמריקה  ועוד", "Погода в мире","");
$FORECAST_ISR = array("Israel", "תחזית לארץ", "Погода в Израиле","");
$IN_TABLE = array("in table", "בטבלה", "показать в таблице","");
$FORECAST = array("Weather Forecast", "מזג-אוויר חזוי", "Прогноз погоды","");
$LIKED_FORECAST = array("Liked and disliked forecasts", "תחזיות אהובות ושנואות", "Любимые и нелюбимые прогнозы","");
$WORLD = array("World", "תחזית לחו''ל", "Прогноз за границей","");
$ISRAEL = array("Israel", "לארץ", "в стране",""); 
$FORECAST_TEMP = array("Which temp is expected at ", "איזו טמפרטורה צפויה בשעה", "Какая температура будет в","");
$THUNDERSTORM = array("thunderstorm", "סופת רעמים", "Гроза","");
$LIGHT_RAIN = array("light rain", "גשם קל", "не большой дождь","");
$HEAVY_RAIN = array("heavy rain", "גשם כבד", "ливень","");
$LIGHT_SNOW = array("light snow", "שלג קל", "небольшой снег","");
$LOCAL_RAIN = array("local rain", "גשם מקומי", "местами дождь","");
$DRIZZLE = array("drizzle", "טפטוף", "морось","");
$SNOW = array("snow", "שלג", "снег","");
$SLEET = array("sleet", "סליט", "дождь со снегом","");
$HAIL = array("hail", "ברד", "град","");
$FOG = array("fog", "ערפילי", "туман","");
$SANDSTORM = array("sandstorm", "סופת חול", "песчаная буря","");
$WARM_WIND = array("warm wind", "רוח חמה", "тёплый ветер","");
$SEVERE_CLOUDS = array("heavy clouds", "עננים כבדים", "грозовые тучи","");
$DUST = array("dust", "אבק", "пыль","");
$DUSTPM25 = array("small ", "אבק קטן", "пыль","");
$DUSTPM10 = array("large", "אבק גדול", "пыль","");
$DUST_THRESHOLD1 = array("Not healthy", "לא בריא", "вредно для здоровья","");
$DUST_THRESHOLD2 = array("Sport activity is not recommended", "לא לעשות ספורט", "не рекомендуется заниматься спортом, более опасный","");
$DUST_THRESHOLD3 = array("small is more dangerous", "הקטן יותר מסוכן", "не рекомендуется заниматься спортом, более опасный",""); 
$SPORT_FORBIDEN = array("You should hold your outside activity", "צריך לצמצם פעילות בחוץ", "","");
$ALERGY = array("allergy", "אלרגיה", "аллергия","");
$TEMPO = array("temporarily", "זמנית", "временно","");
$CLOUDY = array("cloudy", "מעונן", "облачно","");
$MOSTLY = array("mostly", "בד''כ", "обычно","");
$PARTLY = array("partly", "חלקית", "частично","");
$PARTLY_CLOUDY = array("partly cloudy", "מעונן חלקית", "переменная облачность","");
$FEW_CLOUDS = array("few clouds", "כמה עננים", "небольшая облачность","");
$CLEAR = array("clear", "בהיר", "светлое",""); 
$HAZE = array("haze", "מעט אביך", "дымка","");
$MIST_AT_NIGHT = array("mist at night", "ערפילי בלילה", "ночной туман","");
$PROB = array("probably", "יתכן", "может быть","");
$AND = array("and", "ו", "и",""); 
$NIGHT = array("night", "לילה", "ночь","");
$AFTERNOON = array("afternoon", "אחה''צ", "после полудня","");
$NOON = array("noon", "צהריים", "днем","");
$MORNING = array("morning", "בוקר", "утро","");
$EARLY_MORNING = array("morning", "לפנות בוקר", "ранним утром","");
$EVENING = array("evening", "ערב", "вечер","");
$DURING = array("during", "במהלך", "во время","");
$THE = array("the", "ה ", "","");
$OR = array("or", "או", "или","");
$GENERALLY = array("Generally" , "באופן כללי", "В общем","");
$CHANCE_FOR = array("chance of ", "יתכן", "возможно","");
$GOOD_CHANCE_FOR = array("good chance of ", "סיכוי טוב ל", "большая вероятность","");
$LOW_CHANCE_FOR = array("low chance of ", "סיכוי נמוך ל", "небольшая вероятность","");
$ISOLATED = array("isolated", "יחיד", "изолирован",""); 
$OCCASIONALLY = array("occasionally", "מדי פעם", "иногда","");
$AT_TIMES = array("at times", "לפרקים", "временами","");
$ALTERNATELY = array("alternately", "לסירוגין", "поочередно","");
$RAINY = array("rainy", "גשום", "дождливый","");
$EXTREME_WINDS = array("Extreme wind" , "רוח סערה", "Порывистый ветер","");
$STRONG_WINDS = array("Strong wind" , "רוח חזקה", "Сильный ветер","");
$MODERATE_WINDS = array("Moderate wind" , "רוח ערה", "Умеренный ветер","");
$WEAK_WINDS = array("Light wind" , "רוח קלה", "Слабый ветер","");
$EXTREME_WINDS_DESC = array("Sudden side wind, hard to walk in the street" , "רוחות צד פתאומיות, קשה ללכת ברחוב", "Порывистый ветер","");
$STRONG_WINDS_DESC = array("Not comfortable, could blow out some light stuff or laundry" , "מצב לא נוח, יכולה להעיף כביסה או חפצים קלים", "Сильный ветер","");
$MODERATE_WINDS_DESC = array("might be interrupting in some situations" , "מורגש, יכול להפריע במצבים מסוימים, אבל העורבים לא עוזבים את צמרות העצים", "Умеренный ветер","");
$WEAK_WINDS_DESC = array("refreshing in the sun, chilly in the night" , "עמיחי: רוח נושבת נשיקות קלות על עורה. מרענן בשמש, מקרר בצל ובלילה", "Слабый ветер","");
$TEMPO = array("temporarily" , "זמנית", "временно","");
$BECMG = array("becoming" , "ישתנה", "измениться","");
$BECMG_TO = array("to" , "ל", "к","");
$FROM = array("from " , "מ", "от","");
$TO = array("to" , "עד", "до","");
$GIVEN = array("given", "ניתנה", "дана","");
$AT = array("at ", "ב-", "в","");
$CHANCE_OF = array("chance of", "סיכוי ל", "возможность","");
$LATER = array("later", "לקראת סוף היום", "к концу дня","");
$AT_FIRST = array("at first", "בבוקר", "утром","");
$VERY = array("very", " מאד ", "очень","");
$OVERLOOK = array("Outlook", "תשקיף", "прогноз","");
$OVERLOOK_EXP = array("The forecast might change in a higher chance than previous days", "התחזית עשויה להשתנות בסיכוי גבוה יותר מאשר ימים קודמים", "Вероятность изменения прогноза выше чем в предыдущие дни","");
$NIGHT_TEMP_EXP = array("Evening = 20:00 to 24:00. Low temp occurs usually (but not always) in the early morning of the same day", "השעות 20:00 עד 23:00. מינימום מתרחש בד''כ בשעות של לפנות בוקר. את המינימום של אותו לילה תמצאו למחרת", "Вечер = 20:00 по 24:00. Минимальная температура за день как правило рано утром","");
$WHAT_IS_FORECAST = array("What is weather forecast?", "מה זאת תחזית?", "Что такое прогноз?","");
$FORECAST_DESC = array("This forecast is for Jerusalem. For other location nearby you have to increase 0.8 degreee for every 100m decrease in elevation.", "זאת תחזית עבור ירושלים. אם מחפשים יעד קרוב בגובה אחר - צריך להעלות 0.8  מעלות לכל 100 מ' ירידה בגובה.<br/>הזמנים המוזכרים עבור התחזית ל-24 שעות הינם בגדר הערכות ולא מתיימרים לציין זמן מדוייק. כלומר זה יותר בגדר 'ערב', 'בוקר' או 'לילה'. <br/> מה זאת תחזית? עד כמה אפשר לדייק בתחזית? אלה שאלות רלוונטיות שלרוב לא מתייחסים להן בכלל. <br/> אנשים רוצים לדעת אם יירד גשם בשעה 12:35 על עץ התות בחצר תיאטרון החאן. זאת בקשה לא אפשרית כי תחזית אפשר לתת לאיזור ולטווח של שעות, לא לשעה ספציפית ולא למקום ספציפי. זהו פער (בין הרצוי למצוי) שתמיד קיים ותמיד יתקיים בעתיד הנראה לעין, בגלל הצורה שבה תחזית נוצרת.  <br/>  תחזית נוצרת מתנאי התחלה הנלקחים מבלונים המופרחים לאוויר בנקודות מדגמיות בעולם, הלא הן הרדיוסונדות. בארץ יש רק מקום אחד שממנו מופרח בלון כזה. משום שזה מדגמי ובגלל הסיבוכיות של האטמוספירה, אפשר לחזות רק ל-4-5 ימים בדיוק לא רע עבור אזורים ולתת תשקיף לשבוע מראש. לא עבור נקודות על המפה.  <br /> אבל כאן אנחנו מדברים על תחזית לנקודה ספציפית - ירושלים. לכן כבר מעצם הגדרת התחזית יש כאן כשל. כשל שיכול לגרום לאי דיוק, לכאורה, בתחזית. תחזית למיקום ספציפי רגישה הרבה יותר לשינויים קלים במיקומי מערכות. שקע זז כמה קמ ויש לכך השפעה מקצה לקצה בירושלים. כאן באתר יש ניסיון לתת ניואנסים בתחזית שיתאימו לאיזור ירושלים, דבר שלא קיים בתחזיות הכלליות שניתנות במקומות אחרים. <br /> בחורה הולכת במדרכה יבשה בתלפיות, כאשר בגבעה הצרפתית הכל רטוב והיא תגיד לעצמה : 'איפה הגשם?' <br/> כלבלב ילך להשתין להנאתו בגן סאקר ויתפלא שלא יורד גשם, כאשר חברו בתלפיות יעשה סקי מים בשלוליות שליד ביתו. <br /> תחזית שמנבאת גשם שיורד לבסוף ברמאללה ולא דרומה מכך היא עדיין תחזית שהצליחה, מכיוון שמדובר באותו איזור ההר המרכזי. צריך להכיר במגבלות התחזית. <br /> יש גם את האנשים שקמים בבוקר אחרי לילה גשום אל תוך יום יבש וישר חושבים שהתחזית נכשלה. גם גשם בלילה הוא גשם. לילה הוא חלק מהיממה. <br /> אחרי שנאמרו כל הדברים, קורה גם שהתחזית נכשלת וכן, זה מבאס. אבל, הכל בא מתוך רצון לתת שירות שלא קיים ברשת. אז תיהנו!" , " Это прогноз для Иерусалима. Если вы хотите прогноз на близлежащие к Иерусалиму места, прибавьте 0.8° за каждые 100 метров понижения.<br/> Почасовой прогноз на ближайшие сутки может быть не точный. То есть его лучше воспринимать как 'вечер', 'утро' или 'ночь'.<br/> Что такое прогноз? На сколько точен прогноз? Мы очень часто игнорируем эти вопросы.<br/> Мы хотим знать будет ли идти дождь над яблоней, стоящей во дворе театра Хен, в 12:35. Но это невозможно, так как прогноз можно дать только по области и на какой-то период времени. Эта разница между желаемым и возможным всегда была, есть и будет пока не придумают более совершенный способ прогнозирования.<br/> Основанием для всех прогнозов является система воздушных шариков, которые запускаются в ключевых точках по всему миру, под названием Радиозонд. В Израиле есть только одна такая точка, запуская шарик мы получаем несколько замеров. Из-за сложности структуры атмосферы и из-за того, что замеры точечные, есть возможность получить неплохой прогноз только на 4-5 дней, а также получить обзор на ближайшую неделю. Замечу, что прогноз будет по области, а не на точку на карте. Сейчас же мы говорим о прогнозе в Иерусалиме, а не об области радиозонда — это одна из причин неточности прогноза. Прогнозисту приходится делать дополнительные замеры, чтобы получить прогноз в Иерусалиме.<br/> Например девушка идет по сухому тротуару в Тальпиоте в то время как в Гива Царфатит все мокро от дождя и думает 'ну и где же обещанный дождь?'.<br/> Собачка пойдет пописать в Ган Сакер и удивится, что нету дождя, в то время как её друг в Тальпиоте катается по лужам на водных лыжах.<br/> Например, по прогнозу должен был быть дождь в Рамалле но он прошёл южнее, это все равно хороший прогноз так-как прогноз был сделан на область холма, где располагается Рамалла. Нужно знать границы возможностей прогноза.<br/> Ещё пример – человек просыпается с утра после дождливой ночи, а на улице сухо и он уверен, что прогноз был ошибочный. Всё потому, что прогноз правильный на сутки, а ночь, это часть суток.<br/> Кроме всего вышесказанного есть так же ошибки в прогнозе и это огорчает, но надо помнить, что в конечном счёте все это делается ради вашего блага. Получаете удовольствие!","");
/////////////////////////////////////////////////////////////////////
$WHICH_IS = array("which is", "שזה", "который",""); 
$YESTERDAY = array("yesterday", "אתמול", "вчера","");
$TOMORROW = array("tomorrow", "למחרת", "завтра","");
$TODAY = array("today", "היום", "сегодня","");
$NOW = array("Now", "עכשיו", "сейчас","");
$CHANGE = array("change in ", "שינוי", "изменение","");
$MAX = array("Max", "מקסימום", "Максимум","");
$MIN = array("Minimum", "מינימום", "Минимум","");
$MID = array("Mid", "ממוצע", "Середина","");
$SPECIAL_NOTICE = array("Special notice", "שימו לב", "Обратите внимание","");
$PRINT = array("Print this page", "הדפסה", "Напечатать эту страницу","");
$BACK = array("Back", "חזרה", "Назад","");
///////////////////////////////////////////////////////////////////////
$CLOUD_BASE = array("Cloud base", "בסיס ענן", "Основание облака","");
$MOON_PHASE = array("Moon phase", "מצב הירח", "Фаза луны","");
$SUN_PHASE = array("Sun", "השמש", "Солнце","");
$WHOLE_SEASON = array("season", "רב שנתי", "Весь сезон","");
$TILL_NOW = array("till now", "עד עכשיו", "До настоящего времени","");
$DIFF_FROM = array("compared to", "יחסית ל", "по сравнению с","");
$NORMAL = array("normal", "ממוצע", "Нормальный",""); 
$DAYS = array("days", "ימים", "Дней",""); 
$RAINY_DAYS = array("rainy days", "ימי גשם", "дождливые дни","");
/////////////////////////////////////////////////////////////////////////
$GLOBAL_WARMING = array("Warming since 2001", "התחממות בי-ם מ-2001", "Потепление с 2001г","");
$DAILY_LOOP = array("All-day pictures in a clip", "סרטון של כל התמונות של היום", "Сегодняшние фотографии в виде видеоклипа","");
$DAILY_LOOP_ARCHIVE = array("How the day was - by date", "איך היום נראה  - לפי תאריך", "Как выглядел день – по датам","");
$BY_DATE = array("by date", "לפי תאריך", "по датам","");
$SATELLITE = array("Satellite", "לווין", "Спутник","");
$PICTURES = array("Album", "אלבום תמונות", "Альбом","");
$DID_YOU_KNOW = array("Did you know?", "הידעת?", "Знаете ли вы?","");
$ALBUM_DESC = array("Pictures of nature, seasons, snow and more...", "תמונות של עונות השנה, של התחנה, של פלאי טבע מרחבי העולם ועוד...", "Фотографии природы, сезонов года, снега и т.п.","");
$WINTER = array("Winter", "חורף", "Зима","");
$AUTOMN = array("Autumn", "סתיו", "Осень","");
$SPRING = array("Spring", "אביב", "Весна","");
$SUMMER = array("Summer", "קיץ", "Лето","");
$MOBILE_REDIRECT = array("Redirect to mobile page", "לדף מותאם לנייד", "Перенаправление на мобильную страницу","");
$DESKTOP_REDIRECT = array("Redirect to site", "לאתר הכללי", "Перенаправление на сайт","");
$STAY = array("Stay in site", "השאר באתר המלא", "пребывание на сайте","");
$RUNNING_TREKS = array("Running treks", "מסלולי ריצה", "Беговые дорожки","");
$FSEASON = array("what is your favorite season?", "מהי העונה החביבה עליך?", "какой ваш любимый сезон?","");
$LIVE_PICTURE = array("Live Air", "שידור חי", "Прямой эфир","");
$PIC_DESC = array("2 cameras and animation of latest frames", "שתי מצלמות ואנימציה של תמונות אחרונות", "Две камеры и анимация последних кадров","");
$LIVE_STREAM = array("Live Stream", "סרט חי", "Прямое вещание","");
$CAMERA = array("Camera", "מצלמה", "Камера","");
$CAMERA_LOOP = array("latest pictures in a loop", "תמונות אחרונות באנימציה", "последние снимки в виде анимации","");
$TRENDS = array("Trends", "מגמות", "тенденция","");
$DAYS_WITHOUT_RAIN = array("days without rain", "ימים ללא גשם", "дни без дождя","");
$LEFTOVER = array("leftover of", "עודף של", "остатки","");
$LACK = array("missing out", "חסרים", "отсутствующие","");
$COLD_METER = array("not agree? vote!", "לא מסכימים? הצביעו!", "не согласны? Голосуете!","");
$COLD_METER_YES = array("Yes! I agree!", "כן, רוצה לחזק", "я согласен","");
$WEATHER_CLIPS = array("Weather clips", "סרטוני מזג-אוויר", "Видеоролики погоды","");
$ROAD = array("at road", "בכביש", "Дорога","");
$ROAD_EXP = array("The thermometer is on stone. Asphalt could be hotter in the sun.", "המד מונח על אבן. אספלט עשוי להיות חם יותר בשמש", "Термометр находится на камне. Асфальт может быть горячим на солнце.","");
$ROAD_EXP_NIGHT = array("At night it is like the temp in valleys", "בלילה זו הטמפרטורה בעין כרם, עמק המצלבה או הצבאים", "Ночью это похоже на температуру в долинах","");
$DEW_DESC = array("18 - sauna level 1, 20 - sauna level 2, 22 - sauna level 3", "18 -  סאונה רמה 1<br/> 20 - סאונה רמה 2<br/> 22 - סאונה רמה 3 ", "","");
$VALLEY = array("at valley", "בעמק", "в долине","");
$LOW_VALLEY = array("at lowest places", "בנקודה הנמוכה", "в самых низких местах","");
$MOUNTAIN = array("at hill", "בהר", "на холме","");
$NOT_MOUNTAIN = array("not at hill", "לא בהר", "","");
$MOUNTAIN_VALLEY_DIF = array("Diff between mountain and valley", "הבדל בין הר לעמק", "на холме - в долине","");
$DETAILED_BY_DAY = array("detailed by day", "פירוט לפי ימים", "информация по дням","");
/////////////////////////////////////////////////////////////////////////
$EXTREME_HEAT_INDEX = array("Extreme Heat Index", "עומס חום קיצוני", "Экстремально Высокая Температура","");
$HEAVY_HEAT_INDEX = array("Heavy Heat Index", "עומס חום כבד", "Крайне Высокая Температура","");
$MEDIUM_HEAT_INDEX = array("Medium Heat Index", "עומס חום בינוני", "Относительно Высокая Температура","");
$LOW_HEAT_INDEX = array("Low Heat Index", "עומס חום קל", "Легкая Жара","");
$VVHOT = array("Hot as hell","רותח, חם אש-תנור", "Жарко как в печке","");
$VHOT = array("Very hot, not extreme", "חם מאד, לא היסטרי", "Очень жарко, но терпимо","");
$HOT = array("Hot enough for shorts", "חום של לבוש קצר", "Достаточно тепло для шорт","");
$LHOT = array("Hot enough for T-shirt", "חום של טישרט", "Достаточно Тепло для футболки","");
$NHOTNCOLD = array("Neither hot nor cold", "לא חם ולא קר", "Не жарко и не холодно","");
$COLDISH = array("Cool, light jacket", "קריר, ג'קט קל כזה", "Прохладно, лёгкая курточка","");
$LCOLD = array("Chilly","קור מורגש בקטנה", "Прохладно","");
$COLD = array("Cold (coat)", "קור של מעיל", "Холодно","");
$VCOLD = array("Very cold (gloves etc)", "קור ברמה של כפפות", "Собачий холод","");
$VVCOLD = array("Extremely cold", "קור של שלג", "Мороз","");
$HOT_GROUND = array("Hot ground", "קרקע רותחת", "Дорога","");
$GENDER = array("Gender", "מין", "Пол","");
$MALE = array("Male", "גבר", "Мужчина","");
$FEMALE = array("Female", "אישה", "Женщина","");
$NOR_MALE_NOR_FEMALE = array("prefer not to say", "לא רוצה לציין", "не заполнять","");
$GENDER_NOTICE = array("The cold estimator is evaluated from you being", "מדד הקור במחשב זה נגזר מהיותך", "Шкала холода на этом компьютере высчитывается при помощи ","");
$GENDER_NOTICE2 = array("To alter this assumption click <a href=\"https://www.02ws.co.il/station.php?section=survey.php&amp;survey_id=2&amp;lang=0\">here</a>.", " אפשר לשנות את זה <a href=\"https://www.02ws.co.il/station.php?section=survey.php&amp;survey_id=2&amp;lang=1\">כאן</a>.", "Это можно изменить <a href=\"http://www.02ws.co.il/station.php?section=survey.php&amp;survey_id=2&amp;lang=0\">здесь</a>.","");
$SHORTS = array("Shorts. Short pants and t-shirt.", "לבוש קצר. מכנסיים וחולצה קצרים. סנדלים, כפכפים ודומיהם", "Летняя одежда. Шорты, футболка, сандалии, шлёпки и т.п..","");
$TSHIRT = array("T-shirt", "טישרט", "Футболка","");
$LONGSLEEVES = array("long sleeves, it is recommended to take also t-shirt and add or remove layer when necessary", "שכבה דקה, ארוכה או קצרה, תלוי במשתמש, אפשר גם לשלב", "Длинные рукава. Стоит взять с собой футболку, чтобы добавить или снять слой одежды в случае нужды","");
$SUN_SHADE_CLOTH = array("short in the sun, long in the shade", "בשמש קצר, בצל ארוך", "","");
$SWEATSHIRT = array("Sweatshirt", "חולצה ארוכה עבה", "Толстовка","");
$SWEATER = array("Sweater", "סוודר", "Свитер","");
$JACKET = array("Jacket or light coat", "ג'קט או פליז או מעיל קל סטייל יוניקלו", "Толстовка","");
$COAT = array("Coat", "מעיל", "Куртка","");
$RAINCOAT = array("Rain coat", "מעיל גשם", "Дождевик","");
$LIGHTCOAT = array("light coat", "מעיל דק", "Легкая курточка","");
$LIGHTJACKET = array("light jacket", "ג'קט קל", "Легкая толстовка","");
$LAYERS_BELOW = array("1 layer beneath", "שכבה אחת מתחת", "Дополнительный слой одежды","");
$LAYERS_BELOW2 = array("2 layers beneath", "שתי שכבות מתחת וגם גרביונים", "2 дополнительных слоя  одежды и колготки","");
$LAYERS_BELOW3 = array("3 layers beneath, gloves, scarf and warm hat", "3 שכבות מתחת, כפפות, צעיף וכובע וגם גרביונים או גרביים עבים", "3 дополнительных слоя  одежды, шарф, шапка и колготки","");
$LAYERS_BELOW3_PLUS = array("3 layers beneath, gloves, scarf and warm hat, long underwear, thermal clothing", "3 שכבות מתחת, כפפות, צעיף וכובע וגם גרביונים או גרביים עבים, ביגוד תרמי וגטקס", "3 дополнительных слоя  одежды, шарф, шапка и колготки","");
$UMBRELLA = array("Umbrella", "מטריה", "Зонт","");
////////////////////////////////////////////////////////////////////////////
$NOTHING_SPECIAL = array("Nothing Special", "שום דבר מיוחד", "Пустяк","");
$HIGH_DEW_OVER_NIGHT = array("High dew over night - wet grass", "הרבה טל היה הלילה - דשא ורכב רטוב", "Ночью много росы","");
$RAIN_WILL_STOP = array("Rain will stop", "הגשם ייפסק", "Дождь прекратиться","");
$MORE_CLOUDS = array("Much more clouds", "העננים ייתרבו", "Будет больше туч","");
$RAIN_HAS_JUST_STOPPED = array("Break in rain", "הפוגה בגשם", "Дождь взял передышку","");
$RAIN_HAS_GONE = array("Break in rain", "הפוגה בגשם", "","");
$ITS_RAINING = array("Its raining", "יורד גשם", "Идёт дождь","");
$STORMY = array("Stormy", "גשום וסוער", "Гроза","");
$ITS_SNOWING = array("Its snowing", "יורד שלג", "Идёт снег","");
$RAIN_PROB_EXP_TITLE = array("chances explanation", "הסבר על אחוזי גשם", "","");
$RAIN_PROB_EXP = array("low chance (30%) - keep your event outise alive, but consider a situation of rain (plan B).<br /> 
good chance (60%) - fits event which is not deliacate to rain and short breaks can be done under hood.<br /> 
high chance (80%) - does not fit for continues acticity outside. But, what is the probelm with rain coat?", "סיכוי נמוך (30%) - לקיים אירוע בחוץ תוך מודעות למצב שיירד גשם (תכנית גיבוי). <br />
סיכוי בינוני-טוב (50%-60%) - לקיים אירוע בחוץ שלא רגיש לגשם וניתן לעשות הפסקות קצרות תחת מחסה או פשוט להיות עם מטרייה\מעיל גשם. <br /> 
סיכוי גבוה (80%) -  לא מתאים לפעילות רציפה בחוץ. אבל מה הבעיה בעצם להיות עם מעיל גשם או מטרייה?", "","");
$PRESSURE_IS_FALLING = array("Pressure's falling", "הלחץ יורד", "Давление быстро падает","");
$DRASTIC_TEMP_DROP = array("Temp drop", "התקררות", "Температура сильно упала","");
$DRASTIC_PRESSURE_RISE = array("Pressure rise", "עלייה בלחץ-האוויר", "Давление быстро растет","");
$DRASTIC_TEMP_RISE = array("Temp rise", "התחממות", "Температура сильно выросла","");
$DRASTIC_WIND_RISE = array("Wind rise", "הרוח מתחזקת", "Ветер усилился","");
$VERY_DRY = array("Very dry", "יבש מאד", "Очень сухо","");
$DRASTIC_HUM_RISE = array("Humidity rise", "עלייה בלחות", "Влажность сильно повышенная","");
$DRASTIC_HUM_DROP = array("Humidity drop", "התייבשות", "Влажность сильно понижена","");
$HIGH_DUST = array("Air is dusty", "האוויר מאובק", "Воздух запылён","");
$WINDY = array("Windy", "רוחות חזקות", "Сильные ветры","");
$WIND_SHIFT = array("Wind shift", "חיגה ברוח", "Направление ветра меняется","");
$NO_WIND = array("the air stands still", "האוויר עומד", "Воздух неподвижен","");
$WITHOUT_WIND = array("Without Wind", "ללא רוח", "Безветренно","");
$LIGHT_WIND = array("Light Wind", "רוח קלה", "Лёгкий Ветерок","");
$MODERATE_WIND = array("Moderate Wind", "רוח ערה", "Немного Ветрено","");
$VERY_HOT_HEAT_WAVE = array("Hot and Dry", "שרבי", "Жарко и Сухо","");
$WARMER_THAN_AVERAGE = array("above average", "חם מהרגיל", "теплее обычного","");
$COLDER_THAN_AVERAGE = array("below average", "קר מהרגיל", "холоднее обычного","");
$HIGH_HUMIDITY = array("High humidity in sports", "לחות מורגשת בספורט", "Повышенная влажность","");
$SAUNA1 = array("Sauna level 1", "דביק בקיפול של היד", "Повышенная влажность","");
$SAUNA2 = array("Sauna level 2", "סאונה ברמה של דביק בעפעפים", "Повышенная влажность","");
$SAUNA3 = array("Sauna level 3", "סאונה רמה 3 - להזמין אינסטלטור", "Повышенная влажность","");
$LIKE_AVERAGE = array("it is like average", "עכשיו זה כמו הממוצע", "среднестатистический","");
$THERE_IS= array("there's", "יש", "существует","");
$RAIN_SITUATION = array("rainfall situation", "מצב הגשמים", "состояние осадков","");
$YOU_BETTER = array("You had better", "כדאי", "Стоит","");
$CLOSE = array("close", "לסגור", "закрыть","");
$OPEN = array("open", "לפתוח", "открыть","");
$THE_WINDOW = array("the window", "חלון", "окно","");
$OUTSIDE = array("outside", "בחוץ", "снаружи","");
$INSIDE = array("inside", "בפנים", "внутри","");
$VERY_COLD = array("very cold", "קור שלא פוגשים כל יום", "очень холодно","");
$COLD_SUN = array("Cold sun", "שמש שלא תעבור פוליגרף", "Негреющее солнце","");
$HALF_COLD_SUN = array("Half cold sun", "שמש בשקר לבן", "Немного греющее солнце","");
$SHADE = array("(shade)", "בַּצֵּל", "на солнце",""); 
$SUN = array("(sun)", "בשמש", "тень",""); 
$SUN_SHADE = array("Warm in sun, cold in shade", "סהרה בשמש, סיביר בצל", "Холодно в тени, тепло на солнышке","");
$GOOD_TIME = array(array("Good time to stay outside", " טוב לשבת בחוץ או כל דבר אחר", "Советуем выйти сегодня из дома"),
                    array("Good time to stay outside", " טוב לשבת בחוץ ולקשקש", "Советуем выйти сегодня из дома"),
                    array("Good time to stay outside", " טוב לשהות בחוץ כי די נעים לנו", "Советуем выйти сегодня из дома"),
                    array("Good time to stay outside", " שואלים אם כדאי לצאת? אז כן", "Советуем выйти сегодня из дома"),
                    array("Good time for picnic", " טוב לפיקניק", "Советуем выйти сегодня из дома"),
                    array("Good time to stay outside", " וואלה נחמד להיות בחוץ", "Советуем выйти сегодня из дома"),
                    array("Good time to stay outside", " כמה שזה נשמע הזוי, לצאת זה רצוי", "Советуем выйти сегодня из дома"),
                    array("Good time to stay outside", " התנאים בחוץ טיל", "Советуем выйти сегодня из дома"));
$GOOD_LAUNDRY = array("Good time to dry laundry", "זמן טוב לייבש את הכביסה", "Благоприятная погода для сушки белья","");
$SOSO_LAUNDRY = array("Not Ideal time to dry laundry, but acceptable", "לא תנאים אידיאליים לכביסה, אבל אפשרי", "Не идеальная погода для сушки белья, но сушить можно","");
$BAD_LAUNDRY = array("Bad time to dry laundry - because of rain or dust or humidity", "זמן רע לייבוש כביסה בגלל גשם, אבק או לחות", "Из-за дождя, пыли или влажности, не стоит сушить бельё","");
$IN = array("in", "בעוד", "с","");
$REMOVE_LAUNDRY = array("remove laundry", "כדאי להוריד את הכביסה", "удалить белье","");
$WITHOUT_WIND = array("Without Wind", "ללא רוח", "Безветренно","");
$PIVOT_DESC = array ("Assuming idealistic inside temperature of: ", "המטרה של הדף הזה היא למזג את הבית כך שייתקרב כמה שיותר לתחושה הנוחה ביותר לנו. <br/>זה כמובן אינדיבידואלי, לכן צריך לעשות כמה הנחות. ההנחה היא שהטמפרטורה האידיאלית בבית היא: ","");
//////////////////////////////////////////////////////////////////////////////
$RECORDS_LINK = array("When there was 1134 mm rainfall? look here", "מתי ירדו 1134 מ''מ ? הכנסו לכאן", "Когда выпали 1134мм осадков? Можно увидеть здесь","");
$YEARLY_SUMMARY_LINK = array("Yearly summary", "מה קרה בכל חודש? חפשו בסיכום השנתי", "Сводка года","");
$MONTHLY_SUMMARY_LINK = array("Monthly summary", "מה היה בכל יום ויום? הכנסו לסיכום החודשי", "Сводка месяца","");
$KINNERET = array("Kinneret Lake", "מפלס הכנרת", "Озеро Кинерет",""); 
$NEW = array("new", "חדש", "новый",""); 
$LAST_RECORD = array("last record", "שיא קודם", "Прошлый рекорд","");
$ON = array("at", "ב-", "в","");
$YEARLY = array("yearly", "שנתי", "годовой","");
$BROKEN = array("has been broken", "נשבר", "был превзойдён",""); 
$RECORD = array("Record", "שיא", "Рекорд","");
$RECORDS = array("Records", "שיאים", "Рекорды","");
$REPORTS = array("Reports", "דוחות", "Отчёты","");
$HIGH = array("Hi", "גבוה", "Высокий","");
$LOW = array("Lo", "נמוך", "Низкий",""); 
$AVERAGE = array("average", "ממוצע", "Средний","");
$YEARLY_AVERAGE = array("Yearly average", "ממוצע שנתי", "Среднегодовая","");
$MONTH = array("month", "חודש", "Месяц","");
$YEAR = array("year", "שנה", "Год","");
$MONTHS = array("months", "חודשים", "месяцы","");
$MONTHLY = array("monthly", "חודשי", "каждый месяц","");
$DAY = array("Day", "יום", "День","");
$HOURLY = array("Hourly", "שעתי","");
$DAILY_RAIN = array("Daily rain", "גשם היום מחצות", "Дождь начнётся в полночь","");
$STORM_RAIN = array("Storm rain", "גשם במערכת", "Гроза","");
$TOTAL_RAIN = array("Total", "סה'כ עונתי", "Итог сезона","");
$MONTHLY_RAIN = array("Monthly rain", "גשם החודש", "Дождь месяца","");
$SHOW = array("Show", "הצג", "Показать","");
$SEND = array("Send", "שליחה", "Послать","");
$END = array("Send", "סיום", "Послать","");
$CANCEL = array("Cancel", "ביטול", "Отмена","");
///////////////////////////////////////////////////////////////////////////////////
$MORE_INFO_SPAN = array("extend", "מפורט יותר", "больше деталей","");
$ALL_GRAPHS = array("all graphs", "כל הגרפים שיש", "все графики","");
$MORE_THAN = array("more than", "יותר מ-","");
$LESS_THAN = array("less than", "פחות מ-","");
$GRAPH = array("graph", "גרף", "график","");
$FOR = array("for", "ל-", "для","");
$WEEKS = array("Weeks", "שבועות", "Недели","");
//////////////////////////////////////////////////////////////////////////////////
$HISTORY = array("History","היסטוריה", "История","");
$WHAT_HAPPEND = array ("History", "מה היה", "Что было","");
$HAPPENING = array ("Current", "מה עכשיו", "На текущее время","");
$WILL_HAPPEN = array ("Forecast", "תחזית", "Прогноз","");
$MY = array("My 02WS", "אישי", "Мой 02WS","");
$GENERAL = array("General", "כללי", "Общий",""); 
$CURRENT_INSTABLITY = array("Current Instability","אי יציבות כרגע", "Нестабильность на текущее время","");
$MEDIUM = array("Medium","בינוני", "Средний","");
$EXTREME = array("Extreme","קיצוני", "Экстремальный","");
$WEAK = array("Weak", "חלש", "Слабый","");
$STRONG = array("Strong", "חזק", "Сильный",""); 
$INVERSION = array("Inversion","אינברסיה", "Инверсия","");
$RADIOSONDE = array("Radiosonde","רדיוסונדה", "Радиозонд","");
$FIRE_INDEX = array("Fire Index","סכנת שריפה", "Опасность возгорания","");
$DELTA = array("delta","חוזק אינברסיה", "Мощь инверсии","");
$THICKNESS = array("thickness","עובי אינברסיה", "Ширина инверсии","");
$BASE = array("base","בסיס אינברסיה", "Основа инверсии","");
/////////////////////////////////////////////////////////////////////////////////
$LEGEND = array("legend", "מקרא", "Легенда","");
$SOURCE = array("Source","מקור", "Источник","");
$IMS = array("The Israeli Meteorological Service","השירות המטאורולוגי", "Израильский метеорологический центр","");
$MY_STATION = array("My station","התחנה שלי", "Моя установка","");
$RAIN_SEASONS = array("Rain seasons","עונות גשם", "Сезоны дождей","");
/////////////////////////////////////////////////////////////////////////////////
$RAINRATE = array("Rain rate" , "עוצמת גשם", "Характер дождя","");
$DEW = array("Dew Point", "נקודת טל", "Точка Росы","");
$THW = array("THW", "שקלול הרוח והלחות", " Вычисление на основе ветра и влажности","");
$THSW = array("THSW", "שקלול הרוח הלחות והקרינה", "Вычисление на основе ветра, влажности и излучения","");
$AIR_DENSITY = array("Air Density", "צפיפות האוויר", "Плотность воздуха","");
$AIR_QUALITY = array("Air pollution level?", "מה מצב זיהום האוויר?", "Уровень загрязнения воздуха?","");
$HEAT_IDX = array("Heat Index", "עומס חום", "Тепловая нагрузка","");
$WIND_SPEED = array("Wind Speed", "מהירות רוח", "Скорость ветра","");
$WIND_DIR = array("Wind Direction", "כיוון רוח", "Направление ветра","");
$WIND_HIGH = array("High Wind", "משבים", "Порывы ветра","");
$WIND_HIGH_DIR = array("High Wind Direction", "כיוון משבים", "Направление порывов ветра","");
$WIND_RUN = array("Wind Run", "הספק רוח", "Сила ветра","");
/////////////////////////////////////////////////////////////////////////////////
$FULL = array("Full", "מלא", "Полная","");
$NEW = array("New", "חדש", "Новая",""); 
$NEW_MOON = array("New moon", "הירח ריק", "Новолуние","");
$FULL_MOON = array("Full moon", "הירח מלא", "Полнолуние","");
$MOON = array("Moon", "הירח", "Луна","");
$RISE = array("Rise", "זריחה", "Восход","");
$SET = array("Set", "שקיעה", "Закат","");
$SEARCH_IN = array("Search", "חפש", "Искать","");
$BETWEEN = array("Between", "בין", "Между","");
//////////////////////////////////////////////////////////////////////////////////
$CHAT_TITLE = array("Forum", "פורום", "Форум","");
$SYNOP_TITLE = array("Synoptic chart", "סינופטיקה", "");
$MESSAGES = array("Messages and alerts", "הודעות והתראות", "Сообщения и оповещения","");
$PRIVATE_MSG = array("Private message", "הודעה פרטית", "Личное сообщение","");
$PRIVATE_MSG_TO_SENDER = array("Private message to the opener", "הודעה פרטית לפותח השרשור", "Личное сообщение автору","");
$ALERT_MSG_TO_SENDER = array("Get alert when replied", "קבלת התראה על תגובה", "Оповещать когда вы получаете ответ",""); 
$MANAGER = array("02WS Manager" , "מנהל ירושמיים", "Директор 02WS","");
$V_MANAGER = array("Vice Manager" , "סגן מנהל", "Замдиректора","");
$NAME = array("Name" , "שם", "Имя","");
$BODY = array("message" , "הודעה", "Сообщения","");
$WATCH = array("Watch " , "צפייה ב-", "Посмотрите","");
$REPLY = array("Reply" , "תגובה", "Отзыв","");
$REPLYES = array("Replies" , "תגובות", "Отзывы","");
$NEED_TO_REGISTER = array("need to login/register" , "צריך להירשם או להיכנס מחדש", "требуется регистрация или заново войти","");
$ALERTS_PAYMENT_FULL = array("<div class=\"alertspayment\"><a href=\"#opensettings.png\"><img src=\"images/opensettings.png\" alt=\"short term alerts\" width=\"18\" />To get this before everyone click here</a></div>", "<div class=\"alertspayment\"><a href=\"#opensettings.png\">רוצה לקבל את זה לפני כולם? כאן<img src=\"images/opensettings.png\" alt=\"התראות טווח קצר\" width=\"18\" /></a></div>", "Краткосрочные оповещения будут скоро регистрироваться","");
$ALERTS_TO_APP_PROMO = array("That info you can get before everyone else in a push message in the app.", "את כל הטוב הזה אפשר לקבל לפני כולם בהודעת פוש באפליקציה", "Эту информацию вы можете получить раньше всех в push-сообщении в приложении.");
$ALERTS_PAYMENT = array("<div class=\"alertspayment\"><a href=\"#opensettings.png\"><img src=\"images/opensettings.png\" alt=\"short term alerts\" width=\"18\" /></a></div>", "<div class=\"alertspayment\"><a href=\"#opensettings.png\"><img src=\"images/opensettings.png\" alt=\"התראות טווח קצר\" width=\"18\" /></a></div>", "Краткосрочные оповещения будут скоро регистрироваться","");
$SHORT_TERM_DESC = array("Put this code in the setting menu of the app to get short term alerts from 02ws: ", "את הקוד מכניסים בתוך תפריט ההגדרות של האפליקציה.    הקוד שלך למינוי התראות לטווח קצר מאפליקציית ירושמיים", "Краткосрочные оповещения будут скоро регистрироваться","");
$SHORT_TERM_TITLE = array("02WS Short term alerts subscription", "התראות לטווח קצר - ירושמיים", "Краткосрочные оповещения будут скоро регистрироваться","");
$PATREON_LINK = array("<a href=\"https://www.patreon.com/bePatron?c=1347814&rid=2162701\" target=\"_blank\">here</a>", "<a href=\"https://www.patreon.com/bePatron?c=1347814&rid=2162701\" target=\"_blank\">כאן!</a>", "<a href=\"https://www.patreon.com/bePatron?c=1347814&rid=2162701\" target=\"_blank\">Вот</a>","");
$REPLY_EXP = array("click here and then on send" , "לחץ כאן ולאחר מכן על שליחה", "нажмите тут, потом на отправить","");
$REPLY_ENGAGE = array("Use the reply for feedback about the alert or whatever" , "תגובות יתקבלו בשמחה על כל נושא", "","");
$FILTERRING_BY_SUBJECT = array("Filtering by subject", "סינון לפי נושאים", "Отфильтровать по заголовкам","");
$MSG_SUBJECT = array("Message subject", "נושא ההודעה", "Заголовок","");
$LAST_MSG = array("recent" , "הודעות אחרונות", "последние сообщения","");
$LAST_DAY = array("last day" , "יום אחרון", "предыдущий день","");
$LAST_WEEK = array("last week" , "שבוע אחרון", "предыдущая неделя","");
$LAST_MONTH = array("last month" , "חודש אחרון", "предыдущий месяц","");
$WATCH_ALL = array("Watch all messages" , "צפייה בכל ההודעות", "Просмотр всех сообщений","");
$MAN_EXP = array("" , "<li>הודעות מהנהלת האתר מסומנות באדום, על כל שאר ההודעות אין אחריות.</li><li>תעברו על התחזית לטווח קצר והתחזית לטווח בינוני ואם אין מענה לשאלתכם - פרסמו שאלה.</li><li>הפורום לא נועד להשוואות עם תחזיות של אתרים אחרים. זה לא המקום.</li><li>להודעות כפולות שכבר קיימות בלוח לא תנתן תשובה.</li><li>תגובות שאינן קשורות להודעה המקורית תמחקנה. נא להוסיף הודעות או תגובות במקום המתאים להן.</li><li>זה לא וואטסאפפ. תגובות כמו חחחח, וואלה, מדהים לא מתאימות. תכניסו תוכן אמתי שמקדם את הפורום.</li>", "<li>Сообщения администратора сайта красного цвета, администрация сайта не несёт ответственность за другие сообщения.</li><li>Просмотрите короткий и длинный прогноз и только если там нет того, что вы ищите – задавайте вопрос. </li><li>Форум не предназначен для сравнения погоды с другими сайтами. </li><li>На повторяющиеся вопросы не будет повторных ответов. </li><li>Комментарии, которые не имеют отношение к сообщению будут удалены. Пожалуйста комментируйте по теме. </li><li>Это не Watsapp. Пожалуйста не пишите такие коменты как Хахаха, прикол и т.п. Пишите только полезную информацию.</li>","");
$CHECK_EMAIL = array("Check your Email to make your user active. If you so not see anything, check tha spam", "כעת יש לגשת לאימייל שלך כדי לאשר את הוספתך למערכת. אם לא רואים שום דבר, לבדוק בדואר זבל", "Чтобы активировать учётную запись, проверьте электронную почту","");
$USER_ID_EXP = array("User ID (optionally with numbers in it)", "שם משתמש באנגלית, אפשר עם מספרים - לשימוש עתידי", "Имя пользователя (в имени можно также использовать цифры)","");
$DISPLAY_NAME_EXP = array("The name in the forum", "השם שיוצג בהודעות", "Имя, которое будет показано на форуме","");
$NICENAME_EXP = array("The name in the mailing list and in the forum title", "השם הרשמי שיוצג במייל או בהפניה רשמית", "Имя, которое будет показано в электронной почте и на заголовке форума","");
$PERSONAL_COLD_METER_SUGG = array("If you will register you could get personal cold meter and get your full votes", "אם תרשמו (עניין של דקה-שתיים) תוכלו לקבל מדד קור מותאם אישית ותוכלו גם לצפות בכל ההצבעות שלכם", "Только ваши личные голоса будут использованы в создании Шкалы Холода","");
$PERSONAL_COLD_METER_EXP = array("The cold meter will be displayed based on your votes only", "מדד הקור יוצג בהתאם להצבעות שלך בלבד", "Только ваши личные голоса будут использованы в создании Шкалы Холода","");
$VOTE_INSERTED = array("Your vote has been accepted. With that you have joined thousands of daily voters.", "הצבעתך התקבלה ובכך הצטרפת לאלפי המצביעים היומיים", "Ваш голос принят");
$HELLO = array("Hello", "שלום", "Здравствуйте","");
//////////////////////////////////////////////////////////////////////////////////////////
$HOTORCOLD_Q = array("How do you feel outside now in the shade?", "איך ההרגשה בחוץ עכשיו בַּצֵּל?", "Как у вас ощущения в данную температуру?","");
$HOTORCOLD_T = array("Cold meter", "מדד הקור", "Шкала холода","");
$FSEASON_T = array("Best season", "העונה הכי טובה", "Лучший сезон","");
$ONLYONEVOTE = array("Not enough time has passed since the last vote", "מאז שהצבעת בפעם האחרונה לא חלף מספיק זמן", "Прошло не достаточно времени с последнего голосования","");
$TOTAL_VOTERS = array("Total voters", "סה''כ מצביעים", "Сумма проголосовавших","");
$TOTAL_VOTERS_FEMALE = array("Total voters", "סה''כ מצביעות", "Сумма голосов","");
$MOST_POPULAR = array("Most popular", "הכי פופולרי", "Самый популярный","");
//////////////////////////////////////////////////////////////////////////////////////////
$HAPPY = array("Happy", "שמח", "Весёлый","");
$ANGRY = array("Angry", "כועס", "Злой","");
$TIRE = array("Tire", "עייף", "Уставший","");
$EMBARRASED = array("Embarrased", "נבוך", "Смущён","");
$SAD = array("Sad", "עצוב", "Грустный","");
$SATISFIED = array("Satisfied", "מרוצה", "Доволен","");
$IMHOT = array("I'm hot", "חם לי", "Мне жарко","");
$IMCOLD = array("I'm cold", "קר לי", "Мне холодно","");
$DOUBT = array("skeptic", "סקפטי", "скептик","");
$WINK = array("wink", "קריצה", "подмигивание","");
$AMAZED = array("Amazed", "נדהם", "Удивлённый","");
$CONFUSE = array("Confused", "מבולבל", "Запутанный","");
$KISS = array("Kiss", "נשיקה", "Поцелуй","");
$COOL = array("Cool", "רגוע", "Спокойный","");
$CURIOUS = array("Curious", "סקרן", "Любопытный","");
$DIGGING = array("Digging", "יא חופרים", "Выносители Мозгов","");
$PUDENCY = array("Pudency", "ביישן או צנוע", "Стыдливый","");
$HELL = array("Who can beat me", "מי יכול עלי", "Кто на меня","");
//////////////////////////////////////////////////////////////////////////////////////////
$RUN_WALK = array("Run and walk", "הליכה וריצה", "","");
$HUM_LOW = array("Low humidity", "לחות נמוכה", "","");
$HUM_HIGH = array("High Humidity", "לחות גבוהה", "","");
$HUM_NEUTRAL = array("Neutral humidity", "לחות נייטרלית", "","");
$RUN_GENERAL_EXP = array("", "בהליכה ובריצה דרוש פחות ביגוד. בעיקרון שכבה אחת פחות בהליכה ושתיים פחות בריצה. בתנאים רגילים, טמפרטורה דו-ספרתית מאפשרת ריצה עם קצר (פחות מ-15 לכיוון 10 לשקול ארוך, במיוחד אם הפעילות לא ארוכה). חד ספרתית דורשת ארוך עם אביזר חימום כמו כפפות, כובע ומגן-אוזניים. תמיד עדיף אביזר חימום על פני עוד חולצה כי מהחלקים החשופים בורח החום.", "","");
$WIND_HUM_EXP = array("Wind cause chill, humidity makes us feel warmer.", "לחות מחממת - רוח מקררת", "","");
$SUN_EXP = array("Staying in the sun always warms up. Sometimes it is only a couple of degrees, sometimes it is even more than 10 degrees.", "שהות בשמש תמיד מחממת. לעתים רק בכמה מעלות ולעתים ביותר מ-10 מעלות.", "","");
$HIGH_WIND_HIGH_TEMP_EXP = array("High wind - lowering the heat", "רוח חזקה - מצננת את החום", "","");
$HIGH_WIND_EXP = array("High wind - take another layer", "רוח חזקה - קחו עוד שכבה", "","");
$LIGHT_WIND_NIGHT_EXP = array("Wind gives cooler feeling", "הרוח נותנת תחושה קרירה יותר", "","");
$NO_WIND_LOW_TEMP_EXP = array("No wind - good conditions", "אין רוח - תנאים טובים", "","");
$HIGH_WIND_HIGH_TEMP_EXP = array("Wind chills the hot sun", "הרוח מצננת את השמש הלוהטת", "","");
$HIGH_HUM_EXP = array("Humidity gives warmer feeling, sweating more", "הלחות נותנת הרגשה חמה יותר, מזיעים יותר", "","");
$LOW_HUM_LOW_TEMP_EXP = array("Humidity gives chilly feeling, maybe add layer.", "הלחות נותנת תחושה קרה, אולי כדאי להוסיף שכבה", "","");
$LOW_HUM_HIGH_TEMP_EXP = array("Low humidity, classic, drink more.", "לחות נמוכה, קלאסי, שתו יותר", "","");
$SUN_SHADE_DIFF_EXP = array("Much hotter in the sun", "בשמש חם הרבה יותר", "","");
$DID_YOU_KNOW_EX = array(array("Personal cold meter. If you will register and vote and check it in your account, you will get your votes instead of the general public votes of the cold meter.", "מדד קור מותאם אישית. מה זה אומר? מקבלים את ההצבעות שלך (טקסט נטוי על הצד) ולא של כולם או של המגדר שלך אם הצבעת ולא נרשמת. אם בטמפרטורה מסויימת אין הצבעה שלכם - מקבלים הצבעה של כולם. מה צריך לעשות כדי לקבל את זה? להירשם. ", " Личная шкала холода. Что это такое? Шкала холода — это описание ощущения холода в зависимости от текущей Температуры. Например при температуре около 0 будет написано – «собачий холод». При включении этой опции, вы сможете видеть шкалу холода, настроенную на вас, а не общую с другими пользователями. Если вы не настроили вашу шкалу на одну из температур, то для текущей температуры будет показана общая шкала. Ваша личная шкала будет написана курсивным."),
                         array("The lowest temperature in a day is mostly before sunrise. That is correct if the sky is clear and almost without wind.", "הטמפרטורה הנמוכה ביותר ביממה היא לרוב ממש לפני הזריחה, בתנאי שהשמיים בהירים וללא רוח כמעט ", "Самая низкая дневная температура в основном перед восходом солнца. "),
                         array("The highest layer of snow in Jerusalem was 98cm", "שכבת השלג העבה ביותר בהיסטוריה של י-ם הייתה 98 סמ", "Самый высокий слой снега, когда-либо зафиксированный в Иерусалиме, был 98см"),
                         array("You can feel different, depending on sun, wind, humidity, location. So, it is advised to take into account all of those parameters by looking into the `feels like` and locations like mountain and valley.", "ההרגשה בחוץ משתנה ממקום למקום ובתלות בשמש, רוח, לחות. לכן, כדאי להביט ב`מרגיש כמו` ובמיקומים של הר ועמק כדי לקבל תמונה כוללת.", "Вы можете чувствовать себя по-разному, в зависимости от солнца, ветра, влажности, местоположения. Поэтому рекомендуется принимать во внимание все эти параметры, изучая «ощущения» и такие места, как горы и долины."),
                         array("Humidity warms, wind chills. Wind in the valleys tend to be less than in the exposed to west locations.", "לחות מחממת, רוח מקררת. הלחות לא משתנה לרוב בתוך העיר, אבל הרוח חזקה יותר במקומות גבוהים חשופים למערב מאשר בעמקים", "Влажность согревает, ветер холодит. Ветер в долинах, как правило, слабее, чем в местах, подверженных влиянию западного направления."),
                         array("Basic of warming in the cold season is choosing isolated shoes with thermal socks. When it feels warm there it influence all of the body", "הבסיס לחימום טוב של הגוף בעונה הקרה הוא בחירת נעליים מבודדות מהקרקע וגרביים תרמיים. ברגע שחם שם זה משפיע על כל הגוף.", "Основным утеплением в холодное время года является выбор утепленной обуви с термо носками. Когда там становится тепло, это влияет на все тело"),
                         array("Before going out think which type of activity you will do. If it is active one it is advised to remove layer.", "כשיוצאים צריך לחשוב לפני איזה פעילות נעשה ובהתאם לזה לבחור לבוש. אם יוצאים לפעילות אקטיבית כדאי מראש להוריד שכבה", "Перед выходом подумайте, чем вы будете заниматься. Если он активен, рекомендуется удалить слой."));
$DID_YOU_KNOW_SUMMER = array(array("The highest record temperature in Jerusalem is 44C and it happended on August 1881", "הטמפרטורה הגבוהה ביותר שנמדדה בירושלים היתה 44 מעלות בשנת 1881, בתאריכים ה–28 וה–30 לאוגוסט.", "Самая высокая температура в Иерусалиме, 44°, была зафиксирована в период между 28 и 30 августа 1881г "),
                         array("Personal cold meter. If you will register and vote and check it in your account, you will get your votes instead of the general public votes of the cold meter.", " מדד קור מותאם אישית. מה זה אומר? מקבלים את ההצבעות שלך (טקסט נטוי על הצד) ולא של כולם (או של כל הגברים או הנשים בהתאם למגדר שלך). אם בטמפרטורה מסויימת אין הצבעה שלכם - מקבלים הצבעה של כולם. ", " Личная шкала холода. Что это такое? Шкала холода — это описание ощущения холода в зависимости от текущей Температуры. Например при температуре около 0 будет написано – «собачий холод». При включении этой опции, вы сможете видеть шкалу холода, настроенную на вас, а не общую с другими пользователями. Если вы не настроили вашу шкалу на одну из температур, то для текущей температуры будет показана общая шкала. Ваша личная шкала будет написана курсивным."),
                         array("The lowest temperature in a day is mostly before sunrise. That is correct if the sky is clear and almost without wind.", "הטמפרטורה הנמוכה ביותר ביממה היא לרוב ממש לפני הזריחה, בתנאי שהשמיים בהירים וללא רוח כמעט ", "Самая низкая дневная температура в основном перед восходом солнца. "),
                         array("You can feel different, depending on sun, wind, humidity, location. So, it is advised to take into account all of those parameters by looking into the `feels like` and locations like mountain and valley.", "ההרגשה בחוץ משתנה ממקום למקום ובתלות בשמש, רוח, לחות. לכן, כדאי להביט ב`מרגיש כמו` ובמיקומים של הר ועמק כדי לקבל תמונה כוללת.", "Вы можете чувствовать себя по-разному, в зависимости от солнца, ветра, влажности, местоположения. Поэтому рекомендуется принимать во внимание все эти параметры, изучая «ощущения» и такие места, как горы и долины."),
                         array("Humidity warms, wind chills. Wind in the valleys tend to be less than in the exposed to west locations.", "לחות מחממת, רוח מקררת. הלחות לא משתנה לרוב בתוך העיר, אבל הרוח חזקה יותר במקומות גבוהים חשופים למערב מאשר בעמקים", "Влажность согревает, ветер холодит. Ветер в долинах, как правило, слабее, чем в местах, подверженных влиянию западного направления."),
                         array("Before going out think which type of activity you will do. If it is active one it is advised to remove layer.", "כשיוצאים צריך לחשוב לפני איזה פעילות נעשה ובהתאם לזה לבחור לבוש. אם יוצאים לפעילות אקטיבית כדאי מראש להוריד שכבה", "Перед выходом подумайте, чем вы будете заниматься. Если он активен, рекомендуется удалить слой."));
////////////////////////////////////////////////////////////////////////////////////////////
$DUST_EXISTS_IN24HF = array(array("Dust is expected, be aware", "דאגו שהאבק שמגיע לא ייכנס לנשימה ולנשמה", "Ожидается пыль, имейте в виду"),
                         array("Clean air will be replaced with dust", " האבק יגבר בקרוב, כדאי להתכונן ", "Чистый воздух заменит пыль"),
                         array("The horizon is not clean, dust is coming", "כדאי לעקוב אחרי רמות האבק בשעות הקרובות", "Горизонт не чистый")
                         );
$RAIN_EXISTS_IN24HF = array(array("Rain is expected, be aware and plan", "הבטחנו לכם יום גשם והרווחנו עוד יום שמש, סתם, סתם", "Ожидается дождь, знайте и планируйте "),
                            array("Here comes the rain again", "גשם בעיתו והעת מתקרבת", "Вот идет дождь снова"),
                            array("Blue sky, when you gonna learn to rain? soon", "השמיים הכחולים מחכים להפוך לרטובים", "Голубое небо, когда ты научишься дождь? скоро")
                            );
$HIGHWIND_EXISTS_IN24HF = array(array("High wind is expected later on", "רוח חזקה צפויה בהמשך", "Позже ожидается сильный ветер"),
                            array("Trees will feel the wind strength", "העצים ירגישו בקרוב את עוצמת הרוח", "Деревья почувствуют силу ветра"),
                            array("The windmill will fulill its destiny", "תחנת הרוח סוף סוף תהיה יעילה בקרוב", "Ветряная мельница исполнит свое предназначение")
                            );

?>