<?php
include_once("include.php");
include_once("start.php");
include_once("requiredDBTasks.php");
include_once "sigweathercalc.php";
$PARAMS_ARR = array();
$storm->set_rain(getStormRain());
	
$temp_addon = array(abs($yestsametime->get_tempchange())."° ".($yestsametime->get_tempchange() > 0 ? $MORE_THAN[$EN] : $LESS_THAN[$EN])." ".$YESTERDAY[$EN]." \\n".$MAX[$EN].": ".toLeft($today->get_hightemp())."°"." ".$ON[$EN]." ".$today->get_hightemp_time()." \\n".toLeft($today->get_lowtemp())."°"." ".$ON[$EN]." ".$today->get_lowtemp_time()." \\n", 
                    abs($yestsametime->get_tempchange())." ".($yestsametime->get_tempchange() > 0 ? $MORE_THAN[$HEB] : $LESS_THAN[$HEB])." ".$YESTERDAY[$HEB]." \\n".$MAX[$HEB].": ".toLeft($today->get_hightemp())."°"." ".$ON[$HEB]." ".$today->get_hightemp_time()." \\n".$MIN[$HEB].": ".toLeft($today->get_lowtemp())."°"." ".$ON[$HEB]." ".$today->get_lowtemp_time()." \\n");
$temp2_addon = array($yestsametime->get_temp2change()."° ".$DIFF_FROM[$EN]." ".$YESTERDAY[$EN]." \\n".$MAX[$EN].": ".toLeft($today->get_hightemp2())."°"." ".$ON[$EN]." ".$today->get_hightemp2_time()." \\n".toLeft($today->get_lowtemp2())."°"." ".$ON[$EN]." ".$today->get_lowtemp2_time()."] \\n", 
                    abs($yestsametime->get_temp2change())." ".($yestsametime->get_temp2change() > 0 ? $MORE_THAN[$HEB] : $LESS_THAN[$HEB])." ".$YESTERDAY[$HEB]." \\n".$MAX[$HEB].": ".toLeft($today->get_hightemp2())."°"." ".$ON[$HEB]." ".$today->get_hightemp2_time()." \\n".$MIN[$HEB].": ".toLeft($today->get_lowtemp2())."°"." ".$ON[$HEB]." ".$today->get_lowtemp2_time()." \\n");
$temp3_addon = array($MAX[$EN].": ".toLeft($today->get_hightemp3())."°"." ".$ON[$EN]." ".$today->get_hightemp3_time()."] \\n".toLeft($today->get_lowtemp3())."°"." ".$ON[$EN]." ".$today->get_lowtemp3_time()."] \\n", 
                     $MAX[$HEB].": ".toLeft($today->get_hightemp3())."°"." ".$ON[$HEB]." ".$today->get_hightemp3_time()." \\n".$MIN[$HEB].": ".toLeft($today->get_lowtemp3())."°"." ".$ON[$HEB]." ".$today->get_lowtemp3_time()." \\n");
$humidity_addon = array($MAX[$EN].": ".$today->get_highhum()."% ".$ON[$EN]." "." ".$today->get_highhum_time()."\\n", 
                        $MAX[$HEB].": ".$today->get_highhum()."% ".$ON[$HEB]." "." ".$today->get_highhum_time()."\\n");
$dust_addon = array($DUSTPM10[$EN].": ".$current->get_pm10()."\\n   ".$DUSTPM25[$EN].": ".$current->get_pm25()."\\n", 
                    $DUSTPM10[$HEB].": ".$current->get_pm10()."\\n  ".$DUSTPM25[$HEB].": ".$current->get_pm25()."\\n");
$uv_addon = array($MAX[$EN].": ".$today->get_highuv()." ".$ON[$EN]." ".$today->get_highuv_time()."\\n", 
                  $MAX[$HEB].": ".$today->get_highuv()." ".$ON[$HEB]." ".$today->get_highuv_time()."\\n");
$wind_addon = array($NOW[$EN].": ".$current->get_windspd()." ".$KMH[$EN]." - ".getWindInfo($current->get_windspd(), $EN)['windtitle']."\\n"." 10 ".$MINTS[$EN]." ".$AVERAGE[$EN].": ".$min10->get_windspd()." ".$KMH[$EN]." - ".getWindInfo($min10->get_windspd(), $EN)['windtitle']."\\n".$HIGH[$EN]." ".$TODAY[$EN].": ".$today->get_highwind()." ".$KMH[$EN]." ".$ON[$EN]." ".$today->get_highwind_time(), 
                    $NOW[$HEB].": ".$current->get_windspd()." ".$KMH[$HEB]." - ".getWindInfo($current->get_windspd(), $HEB)['windtitle']."\\n"." 10 ".$MINTS[$HEB]." ".$AVERAGE[$HEB].": ".$min10->get_windspd()." ".$KMH[$HEB]." - ".getWindInfo($min10->get_windspd(), $HEB)['windtitle']."\\n".$HIGH[$HEB]." ".$TODAY[$HEB].": ".$today->get_highwind()." ".$KMH[$HEB]." ".$ON[$HEB]." ".$today->get_highwind_time());
$rain_addon = array($RAINRATE[$EN]." ".$TODAY[$EN].": ".$today->get_highrainrate2()."  mm hr".$ON[$EN]." ".$today->get_highrainrate2_time()." \\n".$STORM_RAIN[$EN].": ".$storm->get_rain()." ".$RAIN_UNIT[$EN]."  \\n".$TOTAL_RAIN[$EN].": ".$seasonTillNow->get_rain2()." ".$RAIN_UNIT[$EN]." \\n".$DIFF_FROM[$EN]." ".$TILL_NOW[$EN]." ".$AVERAGE[$EN].": ".$seasonTillNow->get_rainperc()."%"." \\n".$DIFF_FROM[$EN]." ".$AVERAGE[$EN]." ".$WHOLE_SEASON[$EN].": ".$wholeSeason->get_rainperc()."%",
                    $RAINRATE[$HEB]." ".$TODAY[$HEB].": ".$today->get_highrainrate2()." ממ שעה ".$ON[$HEB]." ".$today->get_highrainrate2_time()." \\n".$STORM_RAIN[$HEB].": ".$storm->get_rain()." ".$RAIN_UNIT[$HEB]."  \\n".$TOTAL_RAIN[$HEB].": ".$seasonTillNow->get_rain2()." ".$RAIN_UNIT[$HEB]." \\n".$DIFF_FROM[$HEB]."".$AVERAGE[$HEB]." ".$TILL_NOW[$HEB].": ".$seasonTillNow->get_rainperc()."%"." \\n".$DIFF_FROM[$HEB]."".$AVERAGE[$HEB]." ".$WHOLE_SEASON[$HEB].": ".$wholeSeason->get_rainperc()."%");
$dew_addon = array("",
                    "");

array_push($PARAMS_ARR, array('name' => Parameters::AirPressure, 'title0' => 'Air pressure', 'lang0' => 'Atmospheric pressure is the pressure exerted by the weight of the atmosphere over a certain area. Changes in atmospheric pressure reprsent movement of systems that affects the weather. ', 'title1' => 'לחץ אוויר', 'lang1' => 'לחץ-אטמוספרי הוא הכוח אשר מפעיל עמוד האוויר הנמצא מעל מקום מסוים על יחידת שטח. שינויים בו מייצגים תנועת מערכות המשפיעות על מזג-האוויר.'));
array_push($PARAMS_ARR, array('name' => Parameters::DewPoint, 'title0' => 'Dew point', 'lang0' => $dew_addon[$EN].'The dew point is the temperature the air needs to be cooled to (at constant pressure) in order to achieve a relative humidity (RH) of 100%. At this point the air cannot hold more water in the gas form. ... The higher the dew point rises, the greater the amount of moisture in the air. Values above 20 represent high humidity. Negative values represent low humidity. \n\n16 - humidity is felt during physical activity\n\n18 - Suana level 1\n\n20 - Sauna level 2\n\n22 - Sauna level 3', 'title1' => 'נקודת טל', 'lang1' => $dew_addon[$HEB].'ככל שנקודת הטל גבוהה יותר כך כמות הלחות גבוהה יותר. ערכים של מעל 20 מעלות הם לחות גבוהה. ערכים שליליים הם לחות נמוכה.\n\n 16 - לחות מורגשת בספורט בלבד \n18 - סאונה רמה 1 \n20 - סאונה רמה 2 \n22 - סאונה רמה 3'));
array_push($PARAMS_ARR, array('name' => Parameters::Dust, 'title0' => 'Dust', 'lang0' => $dust_addon[$EN].'\nThere are two types of dust in the air: large and small. Small dust present more danger than the large dust. \nLarge dust above 130 - not healthy\nLarge dust above 300 - it is not recommended to do physical activity \nSmall dust above 38 - not healthy\nSmall dust above 100 - it is not recommended to do physical activity', 'title1' => '  אבק', 'lang1' => $dust_addon[$HEB].'\n אבק גדול מעל 130 - לא בריא\n אבק גדול מעל 300 - לא מומלץ לעשות ספורט\n אבק קטן מעל 38 - לא בריא\n אבק קטן מעל 100 - לא מומלץ לעשות ספורט.\n הקטן יותר מסוכן'));
array_push($PARAMS_ARR, array('name' => Parameters::Humidity, 'title0' => 'Humidity', 'lang0' => $humidity_addon[$EN].'Relative humidity is the ratio between the amount of water vapor in the air and the maximum amount of water vapor that can be contained in the air in a given temperature. Can be expressed by the Mixing ratio or by The steam pressure of the water.', 'title1' => 'לחות', 'lang1' => $humidity_addon[$HEB].'לחות יחסית היא היחס בין כמות אדי המים באוויר לבין הכמות המקסימלית של אדי מים שיכול האוויר להכיל בטמפרטורה נתונה. ניתן לביטוי באמצעות יחס העירוב או לחץ האדים של המים.'));
array_push($PARAMS_ARR, array('name' => Parameters::Radiation, 'title0' => 'Solar radiation', 'lang0' => 'the global sunlight represents a measure of the intensity of the sun\'s rays hitting horizontal terrain.', 'title1' => 'קרינת השמש', 'lang1' => 'קרינת השמש הגלובלית, מידה של עוצמת קרני השמש הפוגעות בשטח אופקי.'));
array_push($PARAMS_ARR, array('name' => Parameters::RainChance, 'title0' => 'What is chance of rain?', 'lang0' => $rain_addon[$EN].'\n\nLow chance (30%) - one should hold an event outside while being aware that there are sopme chances for rain (have a backup plan). \nMedium chance (50-60%) - better to plan an outdoor event that is not sensitive to rain and that can accomodate short breaks under a cover, or just be with an umbrella or rain coat.\nHigh chance (80%) - is not suitable for a continuous outdoor activity. But what\'s the problem using a raincoat or an umbrella?\n', 'title1' => 'מה זה אומר סיכוי לגשם?', 'lang1' => $rain_addon[$HEB].'\n\nסיכוי נמוך (30%) - לקיים אירוע בחוץ תוך מודעות למצב שיירד גשם (תכנית גיבוי)\nסיכוי בינוני-טוב (50%-60%) - לקיים אירוע בחוץ שלא רגיש לגשם וניתן לעשות הפסקות קצרות תחת מחסה או פשוט להיות עם מטרייה או מעיל גשם\nסיכוי גבוה (80%) - לא מתאים לפעילות רציפה בחוץ. אבל מה הבעיה בעצם להיות עם מעיל גשם או מטרייה?'));
array_push($PARAMS_ARR, array('name' => Parameters::RoadTemp, 'title0' => 'Road temperature', 'lang0' => $temp3_addon[$EN].'\n\nThe thermometer is placed on a rock.\nDuring the day, asphalt may be hotter in the sun. \nAt night - The temperature represent the feeling in the lower locations such as The Deers valley, The Arazim valley (The Cedar Valley), The Sultan pool and others.', 'title1' => 'טמפ׳ בכביש', 'lang1' => $temp3_addon[$HEB].'\n\nמד הטמפרטורה מונח על אבן. ביום - אספלט עשוי להיות חם יותר בשמש  בלילה - הטמפרטורה מייצגת את ההרגשה במקומות הנמוכים ביותר כמו עמק הצבאים, הארזים, בריכת הסולטן ועוד.'));
array_push($PARAMS_ARR, array('name' => Parameters::Temp, 'title0' => 'Temperature', 'lang0' => $temp_addon[$EN].'', 'title1' => 'טמפרטורה', 'lang1' => $temp_addon[$HEB].'\n\n'));
array_push($PARAMS_ARR, array('name' => Parameters::UV, 'title0' => 'UV', 'lang0' => $uv_addon[$EN].'UV represent the radiation component that is dangerous to human. It start to become dangerous from index of 8 and above. Light skin is more sensitive to UV radiation than dark skin.\n\nTypes of skin: \n\nI white - always burns, never tans\n\nII white - burns easily, hardly tans\n\nIII light brown - burns at a medium level, tans gradually\n\nIV medium brown - burns minimally, tans quickly\n\nV dark brown - almost never burns, tans well\n\nVI Black - never burns, deep color ', 'title1' => 'מתי כדאי לקיים אירוע בחוץ?', 'lang1' => $uv_addon[$HEB].'\nפרמטר UV משקף את הרכיב מתוך הקרינה שמסוכן לבני אדם. הוא מתחיל להיות מסוכן מ-8 ומעלה. סוג עור בהיר יותר רגיש יותר מסוג עור כהה יותר. סוגי עור:\n .1 לבן - תמיד נשרף, אף פעם לא משתזף\n 2 לבן - תמיד נשרף בקלות, משתזף בקושי\n 3. חום בהיר - נשרף במידה בינונית, משתזף בהדרגה\n 4. חום בינוני - נשרף באופן מינימלי, משתזף מהר\n 5. חום כהה - כמעט אף פעם לא נשרף, משתזף היטב\n6. שחור - אף פעם לא נשרף, צבע עמוק'));
array_push($PARAMS_ARR, array('name' => Parameters::ValleyTemp, 'title0' => 'Valley temperature', 'lang0' => $temp2_addon[$EN].'\n\nThe valley is cooler in the early morning hours and become hotter later in the day. ', 'title1' => 'טמפ׳ בעמק', 'lang1' => $temp2_addon[$HEB].'\n\nבעמק קריר יותר בשעות הבוקר המוקדמות וחם יותר בשעות היום.'));
array_push($PARAMS_ARR, array('name' => Parameters::Wind, 'title0' => 'Wind', 'lang0' => $wind_addon[$EN].'\n\nTypes of wind:\n\nlight wind - (amihay): the wind blows light kisses on her skin. Refreshes in the sun, cools in the shadow and at night\n\nModerate wind - wind is felt and can be irritating, but does not affect birds behaviour. The crows stick to the trees\n\nStrong wind - uncomfortable. The wind can blow light items and laundry\n\nStormy wind - sudden side winds, hard to walk on the street  ', 'title1' => 'מה מצב הרוח?', 'lang1' => $wind_addon[$HEB].'\n\nסוגים של רוח: \nרוח קלה - עמיחי: רוח נושבת נשיקות קלות על עורה. מרענן בשמש, מקרר בצל ובלילה.\n רוח ערה - מורגש, יכול להפריע במצבים מסוימים, אבל העורבים לא עוזבים את צמרות העצים. \nרוח חזקה - מצב לא נוח, יכולה להעיף כביסה או חפצים קלים.\n רוח סערה - רוחות צד פתאומיות, קשה ללכת ברחוב'));

?>