<?php
include_once("include.php");
$PARAMS_ARR = array();
array_push($PARAMS_ARR, array('name' => Parameters::AirPressure, 'title0' => 'What is Air pressure?', 'lang0' => 'Atmospheric pressure is the pressure exerted by the weight of the atmosphere over a certain area. Changes in atmospheric pressure reprsent movement of systems that affects the weather. ', 'title1' => 'מה זה אומר לחץ אוויר?', 'lang1' => 'לחץ-אטמוספרי הוא הכוח אשר מפעיל עמוד האוויר הנמצא מעל מקום מסוים על יחידת שטח. שינויים בו מייצגים תנועת מערכות המשפיעות על מזג-האוויר.'));
array_push($PARAMS_ARR, array('name' => Parameters::DewPoint, 'title0' => 'What is dew point?', 'lang0' => '"The dew point is the temperature the air needs to be cooled to (at constant pressure) in order to achieve a relative humidity (RH) of 100%. At this point the air cannot hold more water in the gas form. ... The higher the dew point rises, the greater the amount of moisture in the air. Values above 20 represent high humidity. Negative values represent low humidity. \n\n16 - humidity is felt during physical activity\n\n18 - Suana level 1\n\n20 - Sauna level 2\n\n22 - Sauna level 3"', 'title1' => 'מה זו נקודת טל?', 'lang1' => 'ככל שנקודת הטל גבוהה יותר כך כמות הלחות גבוהה יותר. ערכים של מעל 20 מעלות הם לחות גבוהה. ערכים שליליים הם לחות נמוכה. 16 - לחות מורגשת בספורט בלבד 18 - סאונה רמה 1 20 - סאונה רמה 2 22 - סאונה רמה 3'));
array_push($PARAMS_ARR, array('name' => Parameters::Dust, 'title0' => 'What is small or large dust?', 'lang0' => 'There are two types of dust in the air: large and small. Small dust present more danger than the large dust. \nLarge dust above 130 - not healthy\nLarge dust above 300 - it is not recommended to do physical activity"', 'title1' => '?מה זה אומר אבק גדול וקטן', 'lang1' => 'באויר קיים אבק גדול ואבק קטן. הקטן יותר מסוכן. אבק גדול מעל 130 - לא בריא. אבק גדול מעל 300 - לא מומלץ לעשות ספורט. אבק קטן מעל 38 - לא בריא. אבק קטן מעל 100 - לא מומלץ לעשות ספורט.'));
array_push($PARAMS_ARR, array('name' => Parameters::Humidity, 'title0' => 'What is humidity?', 'lang0' => 'Relative humidity is the ratio between the amount of water vapor in the air and the maximum amount of water vapor that can be contained in the air in a given temperature. Can be expressed by the Mixing ratio or by The steam pressure of the water.', 'title1' => 'מה זה אומר לחות באויר?', 'lang1' => 'לחות יחסית היא היחס בין כמות אדי המים באוויר לבין הכמות המקסימלית של אדי מים שיכול האוויר להכיל בטמפרטורה נתונה. ניתן לביטוי באמצעות יחס העירוב או לחץ האדים של המים.'));
array_push($PARAMS_ARR, array('name' => Parameters::Radiation, 'title0' => 'Solar radiation', 'lang0' => 'the global sunlight represents a measure of the intensity of the sun\'s rays hitting horizontal terrain.', 'title1' => 'מה זה אומר קרינת השמש?', 'lang1' => 'קרינת השמש הגלובלית, מידה של עוצמת קרני השמש הפוגעות בשטח אופקי.'));
array_push($PARAMS_ARR, array('name' => Parameters::RainChance, 'title0' => 'What is chance of rain?', 'lang0' => 'Low chance (30%) - one should hold an event outside while being aware that there are sopme chances for rain (have a backup plan). \nMedium chance (50-60%) - better to plan an outdoor event that is not sensitive to rain and that can accomodate short breaks under a cover, or just be with an umbrella or rain coat.\nHigh chance (80%) - is not suitable for a continuous outdoor activity. But what\'s the problem using a raincoat or an umbrella?\n', 'title1' => 'מה זה אומר סיכוי לגשם?', 'lang1' => 'סיכוי נמוך (30%) - לקיים אירוע בחוץ תוך מודעות למצב שיירד גשם (תכנית גיבוי). סיכוי בינוני-טוב (50%-60%) - לקיים אירוע בחוץ שלא רגיש לגשם וניתן לעשות הפסקות קצרות תחת מחסה או פשוט להיות עם מטרייה או מעיל גשם.  סיכוי גבוה (80%) -  לא מתאים לפעילות רציפה בחוץ. אבל מה הבעיה בעצם להיות עם מעיל גשם או מטרייה?'));
array_push($PARAMS_ARR, array('name' => Parameters::RoadTemp, 'title0' => 'What is road temperature?', 'lang0' => '"The thermometer is placed on a rock.\nDuring the day, asphalt may be hotter in the sun. \nAt night - The temperature represent the feeling in the lower locations such as The Deers valley, The Arazim valley (The Cedar Valley), The Sultan pool and others."', 'title1' => 'מה זה אומר טמפ׳ בכביש?', 'lang1' => 'מד הטמפרטורה מונח על אבן. ביום - אספלט עשוי להיות חם יותר בשמש  בלילה - הטמפרטורה מייצגת את ההרגשה במקומות הנמוכים ביותר כמו עמק הצבאים, הארזים, בריכת הסולטן ועוד.'));
array_push($PARAMS_ARR, array('name' => Parameters::Temp, 'title0' => 'What is temperature?', 'lang0' => '', 'title1' => 'מה זאת טמפרטורה?', 'lang1' => ''));
array_push($PARAMS_ARR, array('name' => Parameters::UV, 'title0' => 'What is UV?', 'lang0' => '"UV represent the radiation component that is dangerous to human. It start to become dangerous from index of 8 and above. Light skin is more sensitive to UV radiation than dark skin.\n\nTypes of skin: \n\nI white - always burns, never tans\n\nII white - burns easily, hardly tans\n\nIII light brown - burns at a medium level, tans gradually\n\nIV medium brown - burns minimally, tans quickly\n\nV dark brown - almost never burns, tans well\n\nVI Black - never burns, deep color "', 'title1' => 'מתי כדאי לקיים אירוע בחוץ?', 'lang1' => 'פרמטר UV משקף את הרכיב מתוך הקרינה שמסוכן לבני אדם. הוא מתחיל להיות מסוכן מ-8 ומעלה. סוג עור בהיר יותר רגיש יותר מסוג עור כהה יותר. סוגי עור: .I לבן - תמיד נשרף, אף פעם לא משתזף II לבן - תמיד נשרף בקלות, משתזף בקושי III חום בהיר - נשרף במידה בינונית, משתזף בהדרגה IV חום בינוני - נשרף באופן מינימלי, משתזף מהר V חום כהה - כמעט אף פעם לא נשרף, משתזף היטב VI שחור - אף פעם לא נשרף, צבע עמוק'));
array_push($PARAMS_ARR, array('name' => Parameters::ValleyTemp, 'title0' => 'What is Valley temperature?', 'lang0' => 'The valley is cooler in the early morning hours and become hotter later in the day. ', 'title1' => 'מה זה אומר טמפ׳ בעמק?', 'lang1' => 'בעמק קריר יותר בשעות הבוקר המוקדמות וחם יותר בשעות היום.'));
array_push($PARAMS_ARR, array('name' => Parameters::Wind, 'title0' => 'Wind', 'lang0' => '"Types of wind:\n\nlight wind - (amihay): ""the wind blows light kisses on her skin"". Refreshes in the sun, cools in the shadow and at night\n\nModerate wind - wind is felt and can be irritating, but does not affect birds behaviour. The crows stick to the trees\n\nStrong wind - uncomfortable. The wind can blow light items and laundry\n\nStormy wind - sudden side winds, hard to walk on the street  "', 'title1' => 'מה מצב הרוח?', 'lang1' => 'סוגים של רוח: רוח קלה - עמיחי: רוח נושבת נשיקות קלות על עורה. מרענן בשמש, מקרר בצל ובלילה. רוח ערה - מורגש, יכול להפריע במצבים מסוימים, אבל העורבים לא עוזבים את צמרות העצים. רוח חזקה - מצב לא נוח, יכולה להעיף כביסה או חפצים קלים. רוח סערה - רוחות צד פתאומיות, קשה ללכת ברחוב'));

?>