<option   value="http://www.worldweather.org/010/c00033.htm">אדינבורו, סקוטלנד Edinburgh </option>
<option   value="http://www.worldweather.org/037/c00143.htm">אמסטרדם Amsterdam</option>
<option   value="http://www.worldweather.org/014/c00051.htm">אנטליה Antalya</option>
<option   value="http://www.worldweather.org/014/c00047.htm">איסטנבול Istanbul</option>
<option   value="http://www.worldweather.org/093/c00801.htm">אורלנדו Orlando</option>
<option   value="http://www.worldweather.org/008/c00021.htm">אוסלו Oslo</option>
<option   value="http://www.worldweather.org/063/c00177.htm">אתונה Athens</option>
<option   value="http://www.worldweather.org/017/c00060.htm">בודפשט Budapest</option>
<option   value="http://www.worldweather.org/014/c00049.htm">בודרום Bodrum</option>
<option	  value="http://www.worldweather.org/001/c00237.htm">בייג'ין Beijin</option>
<option	  value="http://www.worldweather.org/089/c00233.htm">בנקוק Bangkok</option>
<option	  value="http://www.worldweather.org/053/c00191.htm">בריסל Brussels</option>
<option	  value="http://www.worldweather.org/016/c00059.htm">ברלין Berlin</option>
<option	  value="http://www.worldweather.org/083/c01232.htm">ברצלונה Barcelona</option>
<option	  value="http://www.worldweather.org/087/c00193.htm">ג'נבה Geneva</option>
<option   value="http://www.worldweather.org/067/c00188.htm">דבלין Dublin</option>
<option   value="http://www.worldweather.org/019/c00074.htm">דוברובניק Dubrovnik</option>
<option  value="http://www.worldweather.org/002/c00001.htm">הונג-קונג HonkKong</option>
<option	 value="http://www.worldweather.org/006/c00017.htm">וינה Vienna</option>
<option	 value="http://www.worldweather.org/176/c00606.htm">ונציה Venezia</option>
<option	 value="http://www.worldweather.org/103/c00919.htm">ורנה, בולגריה Varna</option>
<option	 value="http://www.worldweather.org/056/c00264.htm">טורונטו Toronto</option>
<option	 value="http://www.worldweather.org/068/c00183.htm">טוקיו, יפן Tokyo</option>
<option	  value="http://www.worldweather.org/093/c00770.htm">יוסטון Houston</option>
<option	  value="http://www.worldweather.org/013/c00043.htm">ירושלים Jerusalem</option>
<option	  value="http://www.worldweather.org/015/c00054.htm">לובליאנה, סלובניה Ljubljana</option>
<option	  value="http://www.worldweather.org/093/c00781.htm">לאס וגאס Las Vegas</option>
<option   value="http://www.worldweather.org/010/c00032.htm">לונדון London</option>
<option   value="http://www.worldweather.org/093/c00269.htm">לוס אנג'לס Los Angeles </option>
<option   value="http://www.worldweather.org/003/c00002.htm">ליסבון Lisbon </option>
<option   value="http://www.worldweather.org/104/c00202.htm">לרנקה, קפריסין Larnaca </option>
<option   value="http://www.worldweather.org/083/c00195.htm">מדריד Madrid </option>
<option   value="http://www.worldweather.org/107/c00206.htm">מוסקבה Moscow </option>
<option   value="http://www.worldweather.org/176/c00603.htm">מילנו Milano </option>
<option   value="http://www.worldweather.org/016/c00058.htm">מינכן Muenchen </option>
<option   value="http://www.worldweather.org/062/c01055.htm">מרסיי Marseille </option>
<option   value="http://www.worldweather.org/093/c00278.htm">ניו-יורק New York</option>
<option   value="http://www.worldweather.org/066/c00224.htm">ניו-דלהיNew-Delhi</option>
<option   value="http://www.worldweather.org/185/c00300.htm">סידני Sydney </option>
<option   value="http://www.worldweather.org/176/c00602.htm">פירנצה Florence </option>
<option	  value="http://www.worldweather.org/062/c00194.htm">פריס Paris</option>
<option	  value="http://www.worldweather.org/172/c00197.htm">פראג Prague</option>
<option	  value="http://www.worldweather.org/083/c01236.htm">פלמה Palma de Mallorca </option> 
<option	  value="http://www.worldweather.org/071/c00251.htm">ניירובי Nairobi</option>
<option	  value="http://www.worldweather.org/173/c00190.htm">קופנהגן Copenhagen</option>
<option	  value="http://www.worldweather.org/092/c00207.htm">קייב אוקראינהKiev</option>
<option	  value="http://www.worldweather.org/035/c00138.htm">קייפטאון Cape Town</option>
<option	  value="http://www.worldweather.org/136/c01080.htm">ריו דה ז'ינרו Rio De Janeiro</option>
<option   value="http://www.worldweather.org/176/c00201.htm">רומא, איטליה Rome</option>
<option   value="http://www.worldweather.org/087/c00312.htm">ציריך, שוויץ Zurich</option>
<option   value="http://www.worldweather.org/096/c00187.htm">שטוקהולם Shtokholm</option>