<option   value="33">אדינבורו, סקוטלנד Edinburgh </option>
<option   value="538">אוקלנד, ניו-זילנד Auckland </option>
<option   value="143">אמסטרדם Amsterdam</option>
<option   value="51">אנטליה Antalya</option>
<option   value="47">איסטנבול Istanbul</option>
<option   value="801">אורלנדו Orlando</option>
<option   value="21">אוסלו Oslo</option>
<option   value="177">אתונה Athens</option>
<option   value="200">בוקרשט Bucharest</option>
<option   value="60">בודפשט Budapest</option>
<option   value="49">בודרום Bodrum</option>
<option	  value="237">בייג'ין Beijin</option>
<option	  value="233">בנקוק Bangkok</option>
<option	  value="191">בריסל Brussels</option>
<option	  value="59">ברלין Berlin</option>
<option	  value="1232">ברצלונה Barcelona</option>
<option	  value="193">ג'נבה Geneva</option>
<option   value="188">דבלין Dublin</option>
<option   value="74">דוברובניק Dubrovnik</option>
<option  value="1">הונג-קונג HonkKong</option>
<option	 value="17">וינה Vienna</option>
<option	 value="606">ונציה Venezia</option>
<option	 value="919">ורנה, בולגריה Varna</option>
<option	 value="264">טורונטו Toronto</option>
<option	 value="183">טוקיו, יפן Tokyo</option>
<option	  value="770">יוסטון Houston</option>
<option	  value="43">ירושלים Jerusalem</option>
<option	  value="54">לובליאנה, סלובניה Ljubljana</option>
<option	  value="781">לאס וגאס Las Vegas</option>
<option   value="32">לונדון London</option>
<option   value="269">לוס אנג'לס Los Angeles </option>
<option   value="2">ליסבון Lisbon </option>
<option   value="202">לרנקה, קפריסין Larnaca </option>
<option   value="195">מדריד Madrid </option>
<option   value="206">מוסקבה Moscow </option>
<option   value="267">מיאמי Miami</option>
<option   value="603">מילנו Milano </option>
<option   value=58">מינכן Muenchen </option>
<option   value="1055">מרסיי Marseille </option>
<option   value="278">ניו-יורק New York</option>
<option   value="224">ניו-דלהי New-Delhi</option>
<option   value="272">סאן-פרנסיסקו San-francisco </option>
<option   value="277">סיאטל Seattle </option>
<option   value="300">סידני Sydney </option>
<option   value="602">פירנצה Florence </option>
<option	  value="194">פריס Paris</option>
<option	  value="197">פראג Prague</option>
<option	  value="1236">פלמה Palma de Mallorca </option> 
<option	  value="251">ניירובי Nairobi</option>
<option	  value="190">קופנהגן Copenhagen</option>
<option	  value="207">קייב אוקראינהKiev</option>
<option	  value="138">קייפטאון Cape Town</option>
<option	  value="1080">ריו דה ז'ינרו Rio De Janeiro</option>
<option   value="201">רומא, איטליה Rome</option>
<option   value="312">ציריך, שוויץ Zurich</option>
<option   value="187">שטוקהולם Shtokholm</option>
<option   value="274">שיקגו Chicago</option>