<li   value="33">אדינבורו, סקוטלנד Edinburgh </li>
<li   value="538">אוקלנד, ניו-זילנד Auckland </li>
<li   value="143">אמסטרדם Amsterdam</li>
<li   value="51">אנטליה Antalya</li>
<li   value="47">איסטנבול Istanbul</li>
<li   value="801">אורלנדו Orlando</li>
<li   value="21">אוסלו Oslo</li>
<li   value="177">אתונה Athens</li>
<li   value="200">בוקרשט Bucharest</li>
<li   value="60">בודפשט Budapest</li>
<li   value="49">בודרום Bodrum</li>
<li	  value="237">בייג'ין Beijin</li>
<li	  value="233">בנקוק Bangkok</li>
<li	  value="191">בריסל Brussels</li>
<li	  value="59">ברלין Berlin</li>
<li	  value="1232">ברצלונה Barcelona</li>
<li	  value="193">ג'נבה Geneva</li>
<li   value="188">דבלין Dublin</li>
<li   value="74">דוברובניק Dubrovnik</li>
<li   value="168">הלסינקי Helsinki</li>
<li  value="1">הונג-קונג HonkKong</li>
<li	 value="24">וארשה Warsaw</li>
<li	 value="204">וילנה Vilnius</li>
<li	 value="17">וינה Vienna</li>
<li	 value="606">ונציה Venezia</li>
<li	 value="919">ורנה, בולגריה Varna</li>
<li	 value="264">טורונטו Toronto</li>
<li	 value="183">טוקיו, יפן Tokyo</li>
<li	  value="770">יוסטון Houston</li>
<li	  value="43">ירושלים Jerusalem</li>
<li	  value="54">לובליאנה, סלובניה Ljubljana</li>
<li	  value="781">לאס וגאס Las Vegas</li>
<li   value="32">לונדון London</li>
<li   value="269">לוס אנג'לס Los Angeles </li>
<li   value="2">ליסבון Lisbon </li>
<li   value="202">לרנקה, קפריסין Larnaca </li>
<li   value="195">מדריד Madrid </li>
<li   value="206">מוסקבה Moscow </li>
<li   value="267">מיאמי Miami</li>
<li   value="603">מילנו Milano </li>
<li   value="58">מינכן Muenchen </li>
<li   value="1055">מרסיי Marseille </li>
<li   value="278">ניו-יורק New York</li>
<li   value="224">ניו-דלהי New-Delhi</li>
<li   value="272">סאן-פרנסיסקו San-francisco </li>
<li   value="277">סיאטל Seattle </li>
<li   value="300">סידני Sydney </li>
<li   value="602">פירנצה Florence </li>
<li	  value="194">פריס Paris</li>
<li	  value="197">פראג Prague</li>
<li	  value="1236">פלמה Palma de Mallorca </li> 
<li	  value="251">ניירובי Nairobi</li>
<li	  value="190">קופנהגן Copenhagen</li>
<li	  value="207">קייב אוקראינהKiev</li>
<li	  value="138">קייפטאון Cape Town</li>
<li	  value="189">רייקיאוויק (איסלנד) Reykjavik</li>
<li	  value="172">רוביניימי (לפלנד) Rovaniemi</li>
<li	 value="175">ריגה Riga</li>
<li	  value="1080">ריו דה ז'ינרו Rio De Janeiro</li>
<li   value="201">רומא, איטליה Rome</li>
<li   value="312">ציריך, שוויץ Zurich</li>
<li   value="187">שטוקהולם Shtokholm</li>
<li   value="274">שיקגו Chicago</li>